### ISSUE TITLE
Support counts

### ISSUE THREAD

**Issue by BohrShaw** [akhodakivskiy/VimFx#374]
Thus `9x` would approximate "Close tabs to the right".

**Comment by digital-carver** [comment]
Hi, when do these 'fixed in dev' features get into the addons.mozilla site? This is a feature I'm very excited about, and have been looking forward to for the last month or so. Even a development version that appears only at https://addons.mozilla.org/en-US/firefox/addon/vimfx/versions/ would be fine, it's just that setting up the environment, locally compiling addons and keeping them updated is quite a bit of hassle for an average user.
