### ISSUE TITLE
Improvements to hints

### ISSUE THREAD

**Issue by dwaxe** [akhodakivskiy/VimFx#421]
1. Pressing 'q' should cancel hints mode.
2. Less important, but Shift+key in hints mode should open in the opposite way from the chosen hints mode. That is, 'fF' should follow the link in a new tab, while 'FF' should follow it in the current tab.

**Comment by alx741** [comment]
1) Currently Esc cancel hints mode (seems more intuitive -vim like-)
2) +1 to that one!

**Comment by lydell** [comment]
1) Is now possible in the development version.
2) How is this useful?

**Comment by alx741** [comment]
2) Sometimes you change your mind about open the hint in a new tab, so it will be faster than cancel the current one, but thinking bout it a little more... 'f' key is more useful for hint letters as it is right under the finger, maybe 'shift-f' can do the trick?

**Comment by dwaxe** [comment]
2) Try it out in Vimium on Chrome. It feels much more intuitive.

**Comment by lydell** [comment]
> Sometimes you change your mind about open the hint in a new tab,

I see. Please note, though, that the development version is _way_ faster at generating hints so this might not be relevant.

> 'f' key is more useful for hint letters as it is right under the finger, maybe 'shift-f' can do the trick?

I don’t follow here. Mind clarifying? :)

> Try it out in Vimium on Chrome. It feels much more intuitive.

This is how _I_ think about it: “I want to open this link in a new tab, so I’ll use the 'F' command (or the 'gf' command available in the development version)”. That’s, in my opinion, better than: “I want to open this link in a new tab. Hopefully I’ll remember to hold shift while typing the last hint char.”

Also, the following needs to be considered:

- In “f mode”, should the use of the shift key result in 'F' (new background tab) or 'gf' (new foreground tab)? Will users disagree?
- How to deal with non-letter hint chars? For example, `<s-/>` does not exist; it is likely `?`.
- Perhaps we should add a new hints mode command (say, `<c-f>`) that toggles between 'f', 'F' and 'gf'. Or perhaps between 'yf' and 'vf' too. But how do you remember what the current mode is?
- The development version has been optimized so that the 'F' and 'gf' commands get fewer hint markers than 'f'—only for things that can be opened in new tabs. So switching mode is not that simple.

**Comment by dwaxe** [comment]
All good points.

> This is how I think about it: “I want to open this link in a new tab, so I’ll use the 'F' command (or the 'gf' command available in the development version)”. That’s, in my opinion, better than: “I want to open this link in a new tab. Hopefully I’ll remember to hold shift while typing the last hint char.”

I agree. When I browse, I usually know whether I want to open a link in a new tab or not. But sometimes I'm not sure beforehand. Think about it from the perspective of someone who hasn't preplanned their browsing behavior before opening hints mode. We've all been in a situation where we are faced with a number of links and don't know which we'll end up picking. It's easiest to just press 'f' (shift is an extra step), look at the possibilities, and finally choose which link to open.

As it currently stands, you only have the option of opening up a link in the current tab. If you decide you want to open it up in a new tab, tough luck. Exit hints mode and try again.

Thus, the main benefit is keystroke efficiency.

> In “f mode”, should the use of the shift key result in 'F' (new background tab) or 'gf' (new foreground tab)? Will users disagree?

Probably new background tab. It would be nice to allow users to mix and match behaviors though.

> How to deal with non-letter hint chars? For example, <s-/> does not exist; it is likely ?.

Vimium deals with conflicts by canceling hint mode. I think it would be more efficient to just let the user open what they want in a new tab, but maybe Vimium has an insurmountable implementation problem?

> Perhaps we should add a new hints mode command (say, <c-f>) that toggles between 'f', 'F' and 'gf'. Or perhaps between 'yf' and 'vf' too. But how do you remember what the current mode is?

This would be overkill. It would already be more than enough to allow users to mix and match between 'f', 'F', 'gf', and the behaviors open in current tab, open in new background tab, and open in new foreground tab. Many users might prefer 'f' to open in new background tab because it's the most efficient way to open many links quickly.

> The development version has been optimized so that the 'F' and 'gf' commands get fewer hint markers than 'f'—only for things that can be opened in new tabs. So switching mode is not that simple.

If a user in 'f' mode shift-selects a link that cannot be opened in a new tab, it will simply open in the current tab. If a user in 'F' or 'gf' mode shift-selects a link that cannot be opened in the current tab, it will simply open in a new tab.

I think I'm having trouble seeing how it's complicated. Enlighten me?

**Comment by lydell** [comment]
This is now available in the development version ([documentation](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/commands.md#the-f-commands-1).

ctrl and alt are used, but not shift since because it is not possible to consistently reverse the effect of shift on the current key.
