### ISSUE TITLE
Default keyboard shortcut for (Insert Mode - Return to Normal mode), Windows

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#441]
Under Windows 8(maybe older versions too) it's not possible to use Control+Escape, so I propose to use Shift+Escape as default

**Comment by lydell** [comment]
Not possible? Please tell me more! (I've never used Windows 8)

**Comment by TheGreenHabi** [comment]
It's system-wide key combination.

Ctrl + Esc: Switch between Modern Desktop Start screen and the last accessed application
Alt + Esc: Cycle between open programs in the order that they were opened

Only Shift + Esc is free

**Comment by lydell** [comment]
Thanks! We'll change it to `<s-escape>` then.

**Comment by lydell** [comment]
@TheGreenHabi Can `<c-s-escape>` be used on Windows? I want to add a new insert mode command and I plan to use that as the default shortcut.

**Comment by TheGreenHabi** [comment]
Hi!
No, it cannot. `<c-s-escape>` is used to open Task Manager

**Comment by lydell** [comment]
What about `<a-s-escape>`? Or do you have a suggestion for a shortcut?

**Comment by TheGreenHabi** [comment]
This command is used for reverse cycle between open programs. Maybe it's possible to use ` - grace accent? It's close to Escape and not used for anything. Also, I was thinking of <c-space> but it's reserved for Windows Chinese IME

**Comment by lydell** [comment]
The new command will let you run one normal mode command and then return to insert mode again (it's a bit like the `I` command). That's why I wanted something similar to `<s-escape>`. The shortcut must also be unlikely to conflict with a page shortcut, so I think we _have_ to involve a modifier. So grave accent won't work (it is also problematic on layouts such as sv-SE where it is a dead key). Perhaps something like `<s-f1>`?

**Comment by TheGreenHabi** [comment]
`<s-f1>` is great idea! It should work.
