### ISSUE TITLE
Difference between installing from repository and from hdd

### ISSUE THREAD

**Issue by morethanoneanimal** [akhodakivskiy/VimFx#443]
When I install VimFx through addons.mozilla.org everything's fine.

But when I try to build it myself and load extension from disk some pages, especially those with high number of links, (e.g. www.reddit.com) don't work and hints don't show up. I tried master branch, v0.5.14 and v0.5.10 tag. 

Is there something I'm missing?

**Comment by lydell** [comment]
Well, it's difficult to say if you're missing something since you didn't really say what you did.

Perhaps your `coffee` binary is too old? Some people have installed it from Debian's repositories and I think it has version 1.4.x, while 1.5.x+ is required for the master branch (as far as I remember).

By the way, if you're interested in building VimFx you should really check out the develop branch. It's much easier to build VimFx there (have a look at the CONTRIBUTING. md file).

**Comment by morethanoneanimal** [comment]
You were right! It was obsolete binary, it seems to work fine now.
I didn't write exaclty what I did because I suspected i missed something obvious.

Thanks!
