### ISSUE TITLE
Directly open a hint when its the only one

### ISSUE THREAD

**Issue by alx741** [akhodakivskiy/VimFx#463]
Some times there is just one 'clickeable' link in the visible screen, i was thinking that it should be directly open instead of prompt a letter for it, but don't know if there is some reason for don't do that(?)

**Comment by dwaxe** [comment]
To play devil's advocate, the behavior would be slightly unexpected. But I agree because it saves keystrokes.

**Comment by lydell** [comment]
- There's always the risk that you see more than one clickable element on the screen, but VimFx only recognizes one. Then you'd follow a link by mistake.

- You would only save one single keystroke, which would _always_ be the first hint char.

- It would likely appear _slower_ than first generating a hint, because that is faster than loading a page. The 'f' command would appear unresponsive until the page has loaded—and then you might even wonder what just happened.

- You wouldn't see the difference between 'yf' with zero and one link.

- It's an optimization for a too rare case.
