### ISSUE TITLE
Interferes with other extensions' focus

### ISSUE THREAD

**Issue by sharnik** [akhodakivskiy/VimFx#497]
I have a 1password extension which autofocuses some of its fields when run, but it no longer works when vimfx is enabled. If I disable vimfx, it works as before, correctly.

Is there a way I can debug this?

vimfx version: 0.5.17.1
Firefox version: 38.0.1

**Comment by lydell** [comment]
I guess we need an option to disable the "Prevent autofocus" feature. Oh wait, there already is one ;)

But the best thing would be if that feature didn't catch 1password's fields.

**Comment by sharnik** [comment]
My bad, works perfectly when unchecking the feature in preferences.

**Comment by lydell** [comment]
That's just a workaround. We should still fix it.

**Comment by lydell** [comment]
Also interferes with Firebug. See #479.

**Comment by lydell** [comment]
Also interferes with Chinese input method. See #473.

**Comment by JoannesJ** [comment]
Just got a report for my addon QuickMark.
It's the same focus issue.
And VimFx also seems to be hijacking the Esc key.

**Comment by enricostano** [comment]
Getting the same here for every kind of input, I need to disable it to keep browsing.

Firefox Developer Edition 42.0a2 (2015-08-28)
VimFX 0.5.17.1

No other add-on installed, pretty fresh Arch Linux + i3 install. Disabling the *Prevent autofocus* flag doesn't help.

**Comment by lydell** [comment]
I’m starting to notice that VimFx’s autofocus prevention is too invasive, too. Here’s the plan:

1. Set prevent autofocus to disabled by default. <q>VimFx will be nice to your browser and to your habits. Promise.</q> When people become annoyed by autofocus they can enable it.

2. Currently, all focus events that occur more than a certain amount of milliseconds after your last key press or mouse click are suppressed. I think we should suppress all focus events between the start of page load (which is easy to detect) until the user’s first key press or click, and nothing else. This should also be documented, because users need to be aware that they cannot mash their keys for fun while waiting for a page to load if they want autofocus prevention.

3. Add an additional autofocus prevention option that prevents focus events directly when you focus a tab. This annoys me very much on some sites: Each time I come back to that tab some text input has been re-focused.
