### ISSUE TITLE
Labels don't follow elements that move

### ISSUE THREAD

**Issue by sstewartgallus** [akhodakivskiy/VimFx#503]
Suppose, I type the command "vf" to focus on an element. Labels that describe the key to select each element then popup. However, if these elements move, maybe because the page has continued to render or the window resizes, the labels don't follow the elements.

**Comment by lydell** [comment]
Yes, that's true, but would it be worth the trouble?

**Comment by sstewartgallus** [comment]
If it's too difficult that's fair enough then.

**Comment by lydell** [comment]
I mean, were you reporting for correctness sake or because you often bump into this?

**Comment by sstewartgallus** [comment]
Quite often I run into this situation when the page rendering changes as it loads and it is annoying. But looking at https://github.com/akhodakivskiy/VimFx/blob/develop/extension/lib/hints.coffee it seems like it'd be annoying to fix. I think currently the code creates a big box on top of the page and places label elements inside that box that just so happen to be located around where the elements they are supposed to be located are placed. Now personally, I think the more logical approach would be to have some kind of closer association between labels and the elements they are supposed to mark but I have no kind of experience with Firefox's API and I assume that if that were possible you would probably have done that and so to fix this bug you would have to register listeners that either refresh the markers or move them when ever the page layout changes which I think would be kind of hacky. Do you have any better ideas on how to fix this bug?

**Comment by lydell** [comment]
> this situation when the page rendering changes as it loads and it is annoying.

I see what you mean. Happen to me as well sometimes, but I wouldn’t go as far as calling it _often._ But it shows that there’s a real use case.

> I think currently the code creates a big box on top of the page and places label elements inside that box that [are] located around where the elements they are supposed to be located are placed.

Yes, that is correct.

> Now personally, I think the more logical approach would be to have some kind of closer association between labels and the elements they are supposed to mark [...] and I assume that if that were possible you would probably have done that

That is correct, too.

For example, for a link, if we’d insert the marker inside the `<a>` element itself and position the marker absolutely relative to the link the markers would move with the link automatically. However, you can’t do that with all markable elements, such as `<input>`s. One could try to wrap `<input>`s in a `<span>` to achieve the same thing, but that can break lots of styling (`.form-group > input`) and bad scripting (`input.parentNode.previousChild.foo()`).

Another major disadvantage of inserting the markers into the web page is that you have to fight the styles of the page. It’s really difficult to reset all styles so that the markers always look the same. Many times we’ve had to bump the `z-index` to win over some crazy high values some sites use. By having moved the markers out of the page and into the browser chrome all of those issues are gone.

Finally, the “rotate hint markers forward/backward” feature requires all of the markers to be in the same stacking context.

The current way is the best I know of.

> to fix this bug you would have to register listeners that either refresh the markers or move them when ever the page layout changes which I think would be kind of hacky

Refreshing the markers would be a bad idea, I think, because that would likely give the same link a different hint than before the refresh, so that the hint chars you intended to type suddenly activates a whole different link.

Moving them, though, sounds like a good idea. It might be possible to add a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to the entire document. As soon as anything changes the positions of the markers could be re-calculated.

> I have no kind of experience with Firefox's API

Don’t worry, I don’t think you need any for this issue. If you’re familiar with standard DOM methods you should be good to go. A PR for this would be appreciated. Don’t hesitate to ask for help with it if you start hacking one up :)

**Comment by sstewartgallus** [comment]
Why would refreshing the labels generate different ones? If it does that should be a bug shouldn't it?

**Comment by lydell** [comment]
Perhaps we mean different things "refreshing". I thought "completely get rid of the old ones and generate new ones". In that case it'd be a least _some_ differences in hints. Different things on the screen -> different hints. Simple as that. Not a bug to me :)

Did you think some other way?
