### ISSUE TITLE
VimFx API initialization

### ISSUE THREAD

**Issue by parantapa** [akhodakivskiy/VimFx#514]
Hi

I wrote a simple addon using the VimFx API.

https://github.com/parantapa/pbfx/blob/master/lib/main.js

It seems to me, that for my addon to work, VimFx should be loaded before my addon initializes.
Currently I dont seem to be having any problem. But just wanted to know what ensures that VimFx is initialized before my addon? Is there something more I need to do to ensure this?

**Comment by lydell** [comment]
Hi!

Nice to see somebody using the API! :D 

`Cu.import(vimfx_url)`. The only thing required to make that not fail is that there is a JavaScript file on your disk at `vimfx_url`. If you have installed VimFx that is the case (and then the `extensions.VimFx.api_url` pref has been set so you can get `vimfx_url` in the first place).

Initially it was possible to write `let vimfx = Cu.import(vimfx_url)`. But when testing I ran into the problem you describe: My test add-on was loaded before VimFx, which didn't work. That's why I changed to `Cu.import(vimfx_url).getAPI(vimfx => ...)`. `.getAPI` is a super simple function that just registers your callback. When VimFx has loaded your callback is called. So there's nothing you need to do to ensure order. In fact, your addon might already run before VimFx. See [public.coffee](https://github.com/akhodakivskiy/VimFx/blob/develop/extension/lib/public.coffee) if you want to know more.

What do you think about the API so far? Was it difficult to use? Have ever worked with creating addons before?

**Comment by parantapa** [comment]
The API is simple and quite nice. I had to do a little digging around to figure out how to set the key for my custom commands. The documentation isn't there for that one. But it was simple to figure that out from the source.

I don't have much experience writing Firefox addons. I had previously written a simple Firefox addon to save the current url into a text file using the addon sdk system. Also had my own fork of VimFx for couple of custom commands.
