### ISSUE TITLE
Shortcut to open developer tools

### ISSUE THREAD

**Issue by BerraDev** [akhodakivskiy/VimFx#515]
Default keybinds for VimFx rebinds ``SHIFT+CTRL+K`` (Open console tab in developer bar in default Firefox).

There is no option in the ``?`` shortcut settings to set a new shortcut for opening the console tab.

**Comment by fowlslegs** [comment]
c-J is also bound to FF's error console. Perhaps it would be best to replace these two shortcuts w/ < and > or something else at your discretion.

**Comment by lydell** [comment]
`<c-J>` and `<c-K>` have already been changed to `gJ` and `gK` in the development version in order not to clash with Firefox’s default shortcuts.

**Comment by fowlslegs** [comment]
With all due respect that seems tedious when moving multiple tabs
numerous spaces over. Especially with taking your finger on and off
shift and especially because (at least in stable) you have not
implemented integer argument multipliers.

If you want to be more vim-like you would use gt and gT, but if you
want to be more efficient you would use < and > or [ and ]. gJ and gK
seems like a poor choice to me because it breaks vim conventions with no
boost to efficiency.

Just my 2 cents. I'm happy to remap myself if you don't agree :-) And,
as always, thanks devs for your hard work.

This is the first time I've responded to a Github issue comment from
email, so hopefully I'm doing this right.

**Comment by lydell** [comment]
Counts _are_ implemented in the development version :)

**Comment by lydell** [comment]
Added to the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#web-console) section of the wiki.
