### ISSUE TITLE
Vimium-like hints

### ISSUE THREAD

**Issue by mkuts12** [akhodakivskiy/VimFx#536]
Hey, 
I love what you do, really do.
Some things i liked in Vimium for Chromium is the fact the when you use the jk you smoothly go down or up. In VimFx you only make a single jump down or up and then it rushes down really quickly, which is annoying and makes me press jk multiple times instead of holding it.
The other thing is more logical, to me, and consistent labeling of links in the f and F functions. I am used to the fact that s is always the label of the first link in the page, like the YouTube home page in youtube, again in youtube, the k is always the fulscreen button, and sometimes I have labels that are 4 letters long, which is not cool. If you could change that or at least make it an option I would be very grateful.
Lastly, there are options to open link in the current tab, force open in new tab or open multiple links. There is an option in FF to always follow links that open in new tab and this opeion breaks af, because it follows every new tab. Sometime I would like to follow newly opened tab but I have to press FK. I would also love if you caould make it an option that F always follows or make different a new option. I think a solution for this problem could be a macro-like mechanism.

Thank you for your work!

best regards, 
Michael

**Comment by mkuts12** [comment]
I have more requests. I write it here because I don't know if it is ok for me to open many issues and spam you...
The W option in vimium, to open the current tab in different window is useful. I use it often.

**Comment by lydell** [comment]
- Slower j/k scrolling: See #529.
- Follow link in new foreground tab / `af` bug: See #227. 
- Window commands: See #402.

That leaves only the hints labelling to discuss. First, it’d be a lot easier to discuss if you start out reading [how the `f` commands, including hints, work](https://github.com/akhodakivskiy/VimFx/blob/29750c89fc1e0dab6a3a53aa87a8db30948807bc/documentation/commands.md#the-f-commands-1). Here is the most important part:

> VimFx also tries to give you shorter hints for elements that you are more likely to click. This is done by the surprisingly simple rule: The larger the element, the shorter the hint.

That’s how VimFx works. Now, we _could_ implement an alternate, more [Vimium-like algorithm](https://github.com/philc/vimium/blob/34452f22ec4c6403deecb59b73d237bcfa7c964a/content_scripts/link_hints.coffee#L433-L470), but before thinking about that I need to know what you think about the following: YouTube (and many other sites) changes a lot. I know that from experience, since I used to be a fan of [userstyles.org](https://userstyles.org/), adding custom styles to for example YouTube. They broke all the time, because YouTube just kept changing things (as do many others). It requires a really good maintainer to make it work for a longer period of time. My point is, even in Vimium, doesn’t the usual hint for the first link or the fullscreen button change every now and then, because of YouTube’s changes? Isn’t that constant re-learning annoying?

**Comment by lydell** [comment]
Closing because no response. Feel free to comment and re-open.
