### ISSUE TITLE
Notifications discussion

### ISSUE THREAD

**Issue by liuche** [akhodakivskiy/VimFx#576]
Edit by @lydell: Re-purposing this issue to discuss notifications more broadly:

- Should they be enabled by default?
- Should the option be available in the UI?
- Should we come up with an alternate way of showing them?

---

I don't want to be notified when I reach the end of a page in search, for example - there should be a preference to turn off notifications because they can be disproportionately intrusive compared to the information they provide.

**Comment by lydell** [comment]
I added an [advanced option](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#advanced-options) called [notifications_enabled](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#notifications_enabled).

To anyone else wanting to turn off notifications: Add a comment here. If enough people want to, we'll add the option to the settings UI as well.

**Comment by utaal** [comment]
+1 for adding the option, notifications are really intrusive.

**Comment by lydell** [comment]
A thing to ask yourself before turning off notifications: Is it the notifications you dislike, or the way they are displayed? If somebody comes up with a better idea of how to display them, please share it here!

**Comment by loonies** [comment]
I like being notified, but I don't like how it looks, it's intrusive.

I would like to see notification somewhere at the bottom. Two options comes to my mind:

 - Find bar, next to `N of M matches`, but unfortunately find bar is    hidded on next / previous movement.
 - Where link URL is placed when moving over a link or using `zf` VimFx command.

**Comment by utaal** [comment]
With my configuration of Firefox notifications in OSX (it's a system setting) I get a banner and the notification sound almost every time I press (n)ext (I think it's not every time just because I enqueue way too many notifications by moving forward quickly): system/browser notifications (at least, in OSX) were not designed for this rate of events. I think it makes sense to have information on search status - somewhere floating on the page or in place of the URL bubble (as @loonies mentioned) should be fine - I don't think they belong as events sent to the browser's notication API (which, I'm assuming, it's what's in use right now).

**Comment by lydell** [comment]
Using the “URL bubble” might actually be a good idea. It seems pretty easy to do, too:

```js
gBrowser.getStatusPanel().label = 'test'
```

**Comment by lydell** [comment]
Would be useful to hear @willemw12’s thoughts on this (who requested the feature in #398).

**Comment by willemw12** [comment]
I don't dislike the desktop notifications. They are very helpful. However, here are some comments, some of which were already mentioned by others above:
 
- I would except desktop notification more to be coming from background processes, not from the current visible window I am interacting with.
 
- I would prefer a notification on the window itself (similar to the URL tooltips, mentioned in #398), not a notification from the desktop panel.
 
- The desktop notification disappears after a while and I might miss the notification. At least for issue #398, I would prefer the notification only to go away after executing the next command (as is the case in vim) or after an Esc-key press.
 
- The desktop notification did not always appear. Might be a problem with the desktop (Plasma 5).
 
- The desktop notification has an "Activate" button (Plasma 5), which serves no purpose.

**Comment by lydell** [comment]
Alright, looks like we’re moving to URL tooltip-based notifications then!

I guess I need to add a configurable (which also means disableable) timeout after which the notification should disappear. At least I _think_ I’d prefer them to go automatically away after some time.

**Comment by lydell** [comment]
I’ve started working on this now: #600

Questions:

- Currently, the notifications will be shown until you press `<escape>`, or you focus a link. Do we need a timeout?
- Do we still need the pref to disable notifications?

**Comment by hyiltiz** [comment]
They are intrusive; please disable them by default, or show on the lower left corner (using something similar to when you point the cursor to a link to show the link address on the left corner); that is not intrusive.

**Comment by strwbrry** [comment]
They cover up two tabs on the tab toolbar. Way too big and stay up for way too long. Disable by default please this was really annoying.

**Comment by lydell** [comment]
@strwbrry Have you read through the discussion here? Do you _really_ want them disable by default, even if we switch to the proposal to show them in the URL popup?

**Comment by strwbrry** [comment]
Sorry @lydell I *did* read through the discussion and wouldn't mind them if they were unobtrusive, I was just annoyed with them and wrote my original opinion that I came here to write.

They're disabled for me now, I might re-enable them if they appear in the URL pop up to check out the change.

**Comment by lydell** [comment]
Thanks @strwbrry for your input.

> I was just annoyed with them and wrote my original opinion that I came here to write

Just a tip for the future: Going somewhere, quickly dumping an annoyed comment and then leaving does not encourage any developers in any way to fix things :)

**Comment by lydell** [comment]
@strwbrry One more thing, I noticed you wrote "stay up for way too long" – does that mean that you want a configurable timeout if we change to the URL popup proposal?

**Comment by strwbrry** [comment]
@lydell Someone else in this thread mentioned possibly missing the notification if it disappears automatically, and that it should stay visible until the next command is executed. I believe this is the behavior in Vim and I'd be fine with it if the notifications were out of the way.

**Comment by lydell** [comment]
Latest updates from #600:

- Showing the notifications in the URL tootip turned out to be a bad idea, because sometimes the URL tooltip needs to be shown at the same time as a VimFx notification. It also caused problems with the [Status4Evar](https://addons.mozilla.org/firefox/addon/status-4-evar/) add-on.

  Instead I show the notification in a popup identical to the URL popup, but on the opposite side, allowing both to be shown at the same time.

- Notifications are shown until you click them, press a key or switch tab.

- The option to disable notification as been kept, but still won’t be exposed in the settings UI.

- You can now choose to display notifications any way you like by using the public API.

This seems to all work out nicely.

**Comment by prat0318** [comment]
it was very intrusive. disabled it. thanks to the advanced option.
