### ISSUE TITLE
Can't leave text input without going to previous page

### ISSUE THREAD

**Issue by alectic** [akhodakivskiy/VimFx#582]
When I press c-[ it goes back to the previous page. I've looked at the documentation and all the options but I can't find anything about it. Is there something I'm missing?

**Comment by lydell** [comment]
`<c-[>` is not a VimFx command. Perhaps you trigger some other command, perhaps from another add-on?

**Comment by y7x** [comment]
alectic, I had the same problem. Found out that Ctrpl+[ is a default keyboard shortcut in Firefox 42 for "Back". (https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&as=u&redirectslug=Keyboard+shortcuts&utm_source=inproduct)

I disabled this shortcut with this addon which Mozilla recommends on the website above:
https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/

<c-[> doesn't trigger "Back" anymore this way.

Now, I have "blur/close active element" bound to <escape>   and  <c-[> in vimfx, but since the update to 0.6.0, I can't defocus text input anymore on Windows 7 and GNU/Linux. Both on Firefox 42.
Returning to normal mode from hints works with these keyboard shortcuts but it doesn't when in a text field or the url bar for example. Basically, I can't return to normal mode from insert mode anymore.

**Comment by lydell** [comment]
@y7x I don't think you should need to disable the built-in Firefox shortcut. VimFx should be able to override it.

It seems like voth of you have run into #577.

**Comment by alectic** [comment]
@lydell I've set c-] for "blur/close active element" as I did with previous versions of VimFx, forgot to mention it. That's why the confusion, I was expecting it to work because I've set it, but it seems firefox grabs it.

@y7x Thanks for the tip, I had no idea. So it wasn't just the VimFx upgrade, it was also the recent firefox upgrade, they coincided.

**Comment by y7x** [comment]
@lydell Oh, right. Didn't see that closed issue. That resolves it for me, thanks.

**Comment by alectic** [comment]
I installed the extension @y7x mentioned and I've disabled the c-[ shortcut so firefox doesn't grab it anymore. But VimFx doesn't react in any way to escape or to c-[ so it doesn't defocus the text input. @lydell can you provide some insight into that?

**Comment by y7x** [comment]
@alectic putting <force> before it makes it work. As @lydell said, you don't need the extension I told you about.

**Comment by alectic** [comment]
@y7x yes, fixed, thanks. Useful extension though.
