### ISSUE TITLE
Recent update lost hinting on links that previously had hinting

### ISSUE THREAD

**Issue by IDex** [akhodakivskiy/VimFx#584]
Today, as VimFx apparently got updated(hinting got fatter #575). I noticed links I previously could click with VimFx showed no hinting, and were hence unclickable.

As I don't know exactly how VimFx decides what to hint, here is HTML I got from inspector tool:
http://pastebin.com/7QpNi65C

By picking the specific element, the problematic link seems to be 
```html
    <span class="instancename">Module 9 lecture video (66 min)
      <span class="accesshide "> Page
      </span>
    </span>
```

Sadly the site is not accessible publicly so I can't link to it directly, here is a illustrative screenshot. The links in the upper left of the window used to be clickable.
![screenshot_2015-11-10_19-20-03](https://cloud.githubusercontent.com/assets/3442917/11069700/272c5c06-87e0-11e5-8679-f03b6f685841.png)

**Comment by lydell** [comment]
> Sadly the site is not accessible publicly so I can't link to it directly

That sure is sad, and a deal breaker. Sorry!

**Comment by IDex** [comment]
Here is a publicly accessible page with same problem, the affected links are "News Forum" and "General Discussion".
https://mycourses.aalto.fi/course/view.php?id=10122

**Comment by lydell** [comment]
Since VimFx 0.6.0, we use a super-fast Firefox API called [nodesFromRect](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIDOMWindowUtils#nodesFromRect()) to retrieve all elements that are candidates for hint markers. Unfortunately, that API seems to exclude elements with little to no area, such as in your case. We’ll need to investigate if we should move back to the method we used before for retrieving elements, or use a combination.
