### ISSUE TITLE
“Cannot” scroll after blurring element in page with large scrollable element, but entire page is not scrollable

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#585]
1. Open `about:addons`;
2. Navigate to VimFx's preferences;
3. Focus some text input field;
4. Blur by pressing `<escape>`;
5. Try scrolling with `j` or `k` or anything -- it won't work (whereas it should).  All "non-scrolling" commands seem to work fine.

**Comment by lydell** [comment]
That’s because the Add-ons Manager does not scroll the entire page; instead, only a smaller element is scrollable. As mentioned in the changelog:

> **which elements scrolls** when you use VimFx’s
  scrolling commands **has changed.** See [scrolling commands] for more
  information.

[scrolling commands]: https://github.com/akhodakivskiy/VimFx/blob/c790b0fc1127c66bb7b33ccbaf4c0e8090e5530b/documentation/commands.md#scrolling-commands-1

When you first visit the page, that smaller scrollable element is focused automatically, which is why you can scroll it. After having focused something else, such as a text input, it won’t be focused anymore. Then VimFx tries to scroll the entire page, which, in this case, results in nothing happening.

You can re-focus the scrollable area using the `f` or `zf` command.

I have thought about this problem for a long time, but haven’t come up with any better solution. Suggestions welcome!

**Comment by RageYL** [comment]
The same happens when viewing some pdf files.
- the scroll works
- go into ignore mode
- escape from ignore mode
- the scroll do not works any more

It would be nice to keep of last scrolled element. when scrolling:
- if something is focused, scroll it
- if nothing is focused, scroll the last scrolled element

**Comment by rnhmjoj** [comment]
Not sure if related but I can't scroll in [webogram](https://web.telegram.org) anymore.

**Comment by lydell** [comment]
Are you sure that you _cannot?_ Have you _tried_ focusing the scrollable element using `zf` or `f`? (I couldn’t try it out, because I didn’t feel like signing up on that site.)

**Comment by rnhmjoj** [comment]
@lydell yes, I tried what you suggested @d125q to do but didn't have any effect.

**Comment by lydell** [comment]
What does “didn’t have any effect” mean?

**Comment by lydell** [comment]
I found a way to fix this.

**Comment by abastardi** [comment]
How was this handled in the previous version -- everything seemed to work fine in 0.5.x?

Anyway, if the current fix ends up not working properly on a lot of sites, another option might be to just let the page's default behavior take over by passing the associated key presses through to the page. For example, if "j" is hit when the active element is not scrollable, just send a down-arrow key press directly to the page and let the page handle it as it normally would. I think this would work in Gmail and Google Groups, both of which scroll the main content area when the arrow or page-up/page-down buttons are pressed, even if that area is not active.

As an aside, I see you recommended pressing zf or f to focus a scrollable area, but neither zf nor f seem to provide hints that can focus scrollable areas on any pages I try.
