### ISSUE TITLE
Request: Make the "Ignore" feature more visible

### ISSUE THREAD

**Issue by liuche** [akhodakivskiy/VimFx#619]
Either by returning the "Ignore" option to the VimFx button (more ideal), or by making the "Ignore" shortcut much more visible in the shortcuts menu (less ideal). I'd say not being able to turn VimFx off is THE most frustrating experience one can have with VimFx - you're already trying to "not use it".

Clicking on the VimFx button no longer offers the option to blacklist a page, but rather brings up the shortcuts menu. I guess this is helpful if you don't remember all the shortcuts or want to learn new ones, but it means that when I visit new websites where VimFx shouldn't be enabled, or if I'm new to VimFx, I have to read everything on the help overlay (because it's also not searchable).

[Anecdote: It took me a really long time, and many frustrated attempts, to find the Ignore option under Misc (and it's not under "Ignore mode" as "Enable Ignore mode", which would make sense to me. I'm actually unclear what `<s-escape>` even is, `<shift-escape>`? If so just write the `<shift>`.). The content isn't searchable so I have to find something that might work, close the help overlay, try it, have it fail, open the help overlay, etc. After failing to pick the right command about twice, it's just easier to go to the addons page and manually blacklist the url because I know that works.]

**Comment by lydell** [comment]
> Either by returning the "Ignore" option to the VimFx button (more ideal),

Not going to happen. See https://github.com/akhodakivskiy/VimFx/issues/593#issuecomment-155680168.

> or by making the "Ignore" shortcut much more visible in the shortcuts menu (less ideal).

Not a big fan of this idea, but thanks for the suggestion. Let's see what others think.

> I'd say not being able to turn VimFx off is THE most frustrating experience one can have with VimFx

If you're desperate, there's nothing stopping you from hitting the "Disable" buttons in the Add-ons Manager, just like any add-on :)

> you're already trying to "not use it"

Sorry, I don't follow here?

> Clicking on the VimFx button no longer offers the option to blacklist a page, but rather brings up the shortcuts menu. I guess this is helpful if you don't remember all the shortcuts or want to learn new ones,

Yes. It also lets you return to Normal mode. Read all about the button [here](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/button.md).

> when I visit new websites where VimFx shouldn't be enabled

Do you mean "where _I prefer VimFx not to be enabled"? Does that happen often to you?

> if I'm new to VimFx, I have to read everything on the help overlay

So you mean that a new user looking for a way  to blacklist a site has to read through the entire Keyboard Shortcuts dialog? Why? If I were new to VimFx and opened that dialog, I'd just read the title and say to myself: "Keyboard shortcuts? That's not what I'm looking for. Closing."

> because it's also not searchable

Yes, this is a bit unfortunate. If we wanted to use the regular find bar of Firefox, we'd have to inject the dialog into the web page. However, in VimFx 0.6.0, that was deliberately moved away from, because it brings a lot of other issues. Interestingly, Vimium has a similar problem: philc/vimium#1869

> it's not under "Ignore mode" as "Enable Ignore mode", which would make sense to me

In Ignore mode, there is no shortcut to enter Ignore mode. That shortcut only exists in Normal mode. That's why it is located under Normal mode, not Ignore mode.

> I'm actually unclear what <s-escape> even is, <shift-escape>? If so just write the <shift>

You may read all about VimFx's key notation [here](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/shortcuts.md).

> I have to find something that might work, close the help overlay, try it, have it fail, open the help overlay,

No need to close the dialog; you can try shortcuts while it's open.

> After failing to pick the right command about twice, it's just easier to go to the addons page and manually blacklist the url because I know that works.

Not sure I understand this. Do you mean that you try to enter Ignore mode using a shortcut, _think_ that you've succeeded, then press a key and realize you didn't? Look at VimFx's toolbar button: It turns red in Ignore mode.

---

My proposal is to add a **New to VimFx?** section to the documentation, listed at the top of the table of contents, in bold. There, we should explain things that might be interesting to new users as short and simple as possible (providing links to the rest of the documentation):

- What `<s-escape>` means.
- What Ignore mode is, how to enter it, how to exit it, how to use the blacklist option (including the `*` trick to blacklist _every_ site), that the buttons turns red in Ignore mode.
- Link to [Questions and answers](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/questions-and-answers.md).
- Suggest more!

What do you think about this?

Also note that I'm trying to strike a balance between usability for new and possibly less technical users, and users already familiar with Vim and/or some other Vim-style add-on for Firefox, such as Vimperator and Pentadactyl.

**Comment by lydell** [comment]
I’ve adjusted the documentation and made the keyboard shortcuts dialog searchable in the development version, so I’m going to close this.
