### ISSUE TITLE
can't scroll on news.ycombinator.com 

### ISSUE THREAD

**Issue by loops** [akhodakivskiy/VimFx#621]
Commit e1fe9923fa57168764b97adebf04094bcb654f79 breaks scrolling  (j/k/u/d/<space>)  on http://news.ycombinator.com.

**Comment by loops** [comment]
Here is a minimal patch that makes things work.  It seems fragile and I can't even guess whether it will still solve the problem that the original patch was meant to address.  But maybe it will at least point in the correct direction.

```
diff --git a/extension/lib/scrollable-elements.coffee b/extension/lib/scrollable-elements.coffee
index 024e380..d664393 100644
--- a/extension/lib/scrollable-elements.coffee
+++ b/extension/lib/scrollable-elements.coffee
@@ -45,6 +45,7 @@ class ScrollableElements
     @updateLargest()
 
   isScrollable: (element) ->
+    return true if element == @window.document.documentElement
     return element.scrollTopMax  >= @MINIMUM_SCROLL or
            element.scrollLeftMax >= @MINIMUM_SCROLL
 
@@ -67,6 +68,7 @@ class ScrollableElements
   # making it possible for unscrollable elements to slip in. This method tells
   # whether the largest element really is scrollable, updating it if needed.
   hasOrUpdateLargestScrollable: ->
+    return true if @largest == @window.document.documentElement
     if @largest and @isScrollable(@largest)
       return true
     else
```

Having played with things a bit because of this issue, I found another problem that predates e1fe992 and still exists even with the patch above:

1. From the main http://news.ycombinator.com page, navigate to a comment page for any one of the items listed.
2. Use any method to return to the previous page.. for example shift-H
3. None of the scroll keys work  (j/k/u/d/space/etc)

**Comment by loops** [comment]
So for the second problem described above, where scroll keys stop working after going back to the previous page, the offending commit is d41fc98be643e88e5afa7941ccf7bdaa1e7d02bf.   HTH.

**Comment by lydell** [comment]
Thanks for your great bug report @loops!

I was shocked when I found the reason scrolling didn’t work on Hackernews: They don’t have a doctype on their pages, meaning they run in quirks mode! Thought hackers would know that everything is easier in standards mode (_with_ a doctype). Perhaps the site isn’t run by hackers.

Anyway, VimFx needs to be able to handle pages in quirks mode as well. While there was _some_ code for it before, it was not enough since the commit you pointed out. So your patch here was not the solution, but thanks anyway for trying! :+1:

As for your your second problem (returning to the main page by going backwards in history), I could not reproduce it in latest master + your patch. Please open a new issue if you can still reproduce it on latest master.

**Comment by loops** [comment]
Hi Simon, 

Thanks for taking a look at this so quickly.  Your fix works to solve both problems described above.  

Cheers!
