### ISSUE TITLE
Prevent autofocus doesn't work on GitHub search

### ISSUE THREAD

**Issue by loonies** [akhodakivskiy/VimFx#675]
With `Prevent autofocus of text inputs` VimFx preference enabled go to
GitHub search page, enter a search term, and navigate forward/backward
(`[`/`]`). Cursor is captured by the GitHub search input.

**Comment by lydell** [comment]
When you go to the next page of GitHub’s code search results, the page is loaded with AJAX. GitHub then annoyingly focuses its search input. This autofocus cannot be prevented in a reliable way, because the case is indistinguishable from a button whose job is to focus some text input. However, after the `[` and `]` commands we know for sure that we can prevent the next focus. So, I added that. Note though, that the autofocus won't be prevented if you use anything other than the `[` and `]` commands, such as clicking with the mouse or using the `f` command.

**Comment by loonies** [comment]
After reading your comment, it seems funny to me that GitHub focuses
search input aggressively. one would expect to scroll page with the new
results loaded, even without VimFx (using `SPACE` for example), instead
of typing into the search field again. I'm wondering what's their
reasoning behind this.
