### ISSUE TITLE
High CPU usage in hint mode

### ISSUE THREAD

**Issue by nevesnunes** [akhodakivskiy/VimFx#678]
When entering hint mode, CPU usage jumps to nearly 100% and remains like this until we choose a hint or exit from the mode. Maybe there's some busy-waiting involved?

**Comment by d125q** [comment]
Can't reproduce.

**Comment by lydell** [comment]
VimFx polls several times a second for if the elements with hint markers have moved, so that the markers can be moved as well. I didn't notice any performance impact because of this on my system, but apparently it seems to be on yours. Do you consider your system high- or low-performance?

I think an option might be needed, which controls the timeout between each poll. You'd need to raise it. Perhaps we should also raise it by default. And/or not process all marker elements in one go on each poll.

All this is assuming you use VimFx 0.11.0, though. And as @d125q pointed out, a specfic URL where it happens is always helpful. Both of these are pointed out in the [contribution tips](https://github.com/akhodakivskiy/VimFx/blob/master/CONTRIBUTING.md), which you didn't read (even though GitHub asked you to) ;)

**Comment by lydell** [comment]
I just measured this a bit more on my system. While I can't tell just by looking and listening and using my computer, the system monitor _does_ show a noticeable rise in CPU usage while in hints mode, but on my system it does not rise to 100%.

I tried to increase the poll interval from lowest possible to lowest possible plus 15ms. Then I couldn't see any CPU rise anymore, and I couldn't see any difference in the updating of hint marker positions either. If I added 20ms I started seeing stuttering movement of the markers.

Hopefully, raising the poll timeout by 15ms works for everyone, which would be good since we could avoid adding an option. The best thing would be if we could test it on your computer before releasing. Would you like to do so? If so, I'll come back with instructions.

**Comment by lydell** [comment]
@nevesnunes Never mind, I added the `hints_sleep` option anyway.
