### ISSUE TITLE
VimFx config file/add-on and extension signing

### ISSUE THREAD

**Issue by loops** [akhodakivskiy/VimFx#682]
The ability to make local customizations to VimFX is a really great ability.  Unfortunately it requires the ability to install a local unsigned "Addon" to Firefox which is something that will no longer be possible with new versions of Firefox:

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

It would be nice to have a fix for this in place before the new version is released.

**Comment by lydell** [comment]
Yeah, I've know this for some time, which is also why I briefly mention it in the documentation. It sucks.

I anyone has an idea on how to improve on the situation I'm more than happy to hear it. At the moment I have no idea what to do.

**Comment by evaryont** [comment]
Would it be too much trouble to support reading user files from the filesystem? Would that make it pass Mozilla's review?

**Comment by lydell** [comment]
I'm working on something like that. I'm pretty sure it'll pass, since we already kind of do it with the current public API.

**Comment by lydell** [comment]
So, after I wrote my last comment I realized that while it’s OK for VimFx to _export_ its public API the way it does, it’s not OK for other extensions to load it this way, because that’d mean arbitrary script loading for that extension, which is not allowed. So my argument for the proposed config file loading is invalid.

So I asked over at the [Mozilla Discourse](https://discourse.mozilla-community.org/): https://discourse.mozilla-community.org/t/is-running-a-user-specifed-js-file-allowed/6809

The current idea is:

- Remove the public API entirely. The API will only be available to config files, which will be loaded in a new way (see below). While the idea of allowing other extensions to load VimFx’s public API and extend VimFx is neat, I don’t think it’ll ever be used. So it’s better to remove it to keep things simple.

- There will be no config file support in the official VimFx version distributed on AMO.

- Config file support _will_ be included in the “unlisted” version of VimFx available in [GitHub releases](https://github.com/akhodakivskiy/VimFx/releases).

This is how config files will work in the “unlisted” version:

There will be an advanced pref called `config_files_directory` which lets you specify a directory in which VimFx will load config.js and frame.js (very similar to today’s approach). These will automatically be passed VimFx’s API. They will be as powerful as creating a full extension manually (like it’s done today).

Pros:

- Simple.
- VimFx can continue to be listed on AMO.
- Easier to get started with a config file. Less boilerplate.
- No need to install Firefox Developer Edition just to be able to use a config file.
- Most people don’t use a config file anyway.

Cons:

- Advanced users have to install a different version. Not a big deal, though?
- You lose automatic updates if you install the “unlisted” version. This could be worked around by keeping the AMO installed but disabled and watch it for updates. Or perhaps advanced users don’t care. They keep track of the VimFx development anyway.

**Comment by loops** [comment]
This sounds workable.  But since unsigned addons will no longer be allowed, how will the unlisted version be loaded into Firefox.  Doesn't it need to still be signed by mozilla to be acceptable to Firefox?

**Comment by lydell** [comment]
The unlisted version (which already exists in GitHub releases, but still is
functionally identical to the AMO version) _is_ signed.

https://wiki.mozilla.org/Addons/Extension_Signing:

> How do I get my add-ons signed if they are not hosted on addons.mozilla.org (AMO)?
>
> You will need to create an AMO account and submit your add-on. There will be an option where you indicate the add-on won't be listed on AMO, and you'll be able to submit your add-on files without having them published on the site. Please read the Distribution Policy for more details.
>
> How does the signing process work for unlisted add-ons?
>
> For unlisted add-ons, files submitted for signing will go through an automated review process. If they pass this review, they are automatically signed and a download link is sent back to the developer. This process should normally take seconds. If the file doesn't pass review, the developer will have the option to request a manual review, which should take less than two days. This is not the same process that currently applies to AMO add-ons, which has been typically slower.

**Comment by lydell** [comment]
This is fixed in the develop branch now. I’ll try to get it into the AMO version, but if that fails we’ll use the backup plan of only including config file support in the GitHub releases version.

The coolest thing about this change is the added `zr` command. It reloads the config file instantly. No need to restart Firefox after each change anymore!

**Comment by loops** [comment]
Tried this out and it works great!

The main reason I was previously using a frame.js was for custom hint matching on a few web sites.  But when I tried your new version, the website was working even without my frame.js...  I was confused until I read in the git history that you have added support for "data-" attributes matching.

So, I don't actually need a frame.js any more but I did play around with the new API to see how it would be done if I needed it.. The conversion was very easy and straightforward of course -- well done!  You're really doing a great job.  The quality of commit messages in the Git history is a shining example of how version control SHOULD be done.

Thanks for these changes.  Will cross my fingers for it to get into AMO :-)

Cheers.
