### ISSUE TITLE
VimFx 0.12 remains active in some textareas, preventing proper text entry

### ISSUE THREAD

**Issue by ronjouch** [akhodakivskiy/VimFx#691]
In some `<textarea>`s under imprecise circumstances, VimFx remains active. As a result, when typing for example `t`, instead of adding the `t` character to the textarea, a new tab is opened :-/

I tried to create a minimal reproduction scenario, but so far I could only reliably reproduce the issue on non-public sites. One of them is the textarea for Pull Request comments at my work's BitBucket, but the problem doesn't happen on a public project like [this one](https://bitbucket.org/controlsfx/controlsfx/pull-requests/568/keyboard-shortcuts-should-be-usable-when/diff).

Is there anything I can do to narrow down to a reliable test case, or help us find what could trigger the issue? Thanks for VimFx :)

Environment: VimFx 0.12 on Firefox aurora 46.0a2 (2016-02-10) on Ubuntu Linux 14.04.3LTS x86_64. 9 other addons installed.

**Comment by lydell** [comment]
Play with the web console. Remove nodes in it until you have as little as possible left. Sometimes you remove too much; then reload the page and try again. Finally, try to copy the remaining parts as HTML and load that separately. If the bug still reproducible in the copied HTML, paste it here and we can try to fix it. If it is not reproducible in the copied HTML, there is probably JavaScript involved as well. That’s trickier to get right. Again, the web console is great, because it shows nodes with event listeners on them, which is a good clue. You can also try to narrow down which `<script>` tag is responsible, and then use look at it in the debugger (enabling its the “Auto prettify minified sources” option) to see what it does. You can also add the following code after [vim-frame.coffee#84](https://github.com/akhodakivskiy/VimFx/blob/8c8b712bbc489b6acc1c8bd0368aedefed21bff1/extension/lib/vim-frame.coffee#L84) to see what element is focused when pressing keys and what type of element VimFx thinks it is:

```coffee
console.log 'focusType', focusType, event.originalTarget
```

**Comment by ronjouch** [comment]
@lydell okay, will come back if I can get to something. Thanks for the hints!

**Comment by ronjouch** [comment]
Couldn't narrow down to the cause of the issue, but it's fixed in 0.13 :)
