### ISSUE TITLE
Opened links don't keep history from BackTrack Tab History

### ISSUE THREAD

**Issue by muflax** [akhodakivskiy/VimFx#720]
Steps to reproduce:

1. Install [BackTrack Tab History](https://addons.mozilla.org/en-US/firefox/addon/backtrack-tab-history/) so that links that get opened in new tabs keep the back history of the original tab. 
2. Open link in new tab through VimFX link hint.

Expected result: History is preserved. (Works with just Ctrl + Left Click etc.)

Actual result: History is not preserved. :(

Keeping tab history is a known bug/feature request for over a decade now, and BackTrack Tab History is merely the latest mostly-working workaround. [Tab History Redux](https://github.com/cfinke/Tab-History-Redux/) still works with the latest Firefox and VimFX, but has some bugs of its own, so I'd like to switch to BackTrack Tab History.

[BackTrack Tab History's support forum](http://forums.mozillazine.org/viewtopic.php?f=48&t=2896859) has notes about addon compatibility. Unfortunately, I don't understand any of the details, so I don't know how to make both addons compatible, or even whose fault it is.

(I posted this bug report in the forum too.)

VimFx version: 0.13.2
BackTrack Tab History version: 0.8pre7
Firefox version: 45.0.1
OS: Linux (Gentoo)
Keyboard language: custom
Worked before: No

**Comment by lydell** [comment]
Thanks for your excellent bug report!

I read through the [developer of BackTrack Tab History's answer](http://forums.mozillazine.org/viewtopic.php?p=14581991#p14581991) to your post in their support forum, and that really helped me come up with a solution. As a bonus, it also allowed me to remove some special code for the Tree Style Tab extension. :)

I've pushed the fix to the development branch, because I want to test it out for at least a few days before releasing it.

**Comment by muflax** [comment]
Nice! Thanks for the quick fix. :)
