### ISSUE TITLE
No hint on a certain link (heise.de)

### ISSUE THREAD

**Issue by cbaumhardt** [akhodakivskiy/VimFx#742]
Steps to reproduce:

1. Visit a www.heise.de article, e.g. http://www.heise.de/newsticker/meldung/Microsoft-fuehrt-dynamische-Blacklist-fuer-allzu-simple-Passwoerter-ein-3221502.html
2. Scroll down to see the link that says "Kommentare lesen" (or use Firefox search for that)
3. Press f or af

Expected result:  hints appear, one of them on top of the "Kommentare lesen" link

Actual result:       hints appear, but none of them on top of the "Kommentare lesen" link:

![example](https://cloud.githubusercontent.com/assets/15808443/15630731/661a1c78-2547-11e6-9aa0-2b6718f9e53d.jpg)

VimFx version: 0.15.1
Firefox version: 46.0.1
OS: Debian Jessie
Keyboard language: en-US
Worked before: No
Example URL(s): http://www.heise.de/newsticker/meldung/Microsoft-fuehrt-dynamische-Blacklist-fuer-allzu-simple-Passwoerter-ein-3221502.html

**Comment by lydell** [comment]
First: Thanks for your excellent report! It makes fixing things so much more fun when it’s super easy to reproduce the problem.

This happens because the icon to the left of “Kommentare lesen” actually covers the link a few pixels on the left. You can try that with the mouse: If you put the mouse pointer in the middle of the link, the link will be underlined, the mouse pointer will change to a hand and the link is clickable. But if you put the mouse pointer to the far left of the link (on the vertical bar of the “K”), the link is _not_ underlined, the mouse pointer stays normal and the link is _not_ clickable.

That’s badly written CSS! If you really feel like it, you could contact the site about it. :)

VimFx checks that the left part of a markable element isn’t covered by some other element. If it is, it gets no hint. This is very useful on sites with tons of links and dropdown menus. Not getting hints for covered elements makes sure that you don’t accidentally click a link behind a dropdown menu when you wanted to click something _inside_ the dropdown menu.

It is too slow to check if every pixel of an element is covered by something else or not, so we only check one pixel to the far left, and, if that fails, once to the right of the element that covers at the far left. This works fine in most cases.

So why doesn’t it work in this case? Well, the icon to the left of “Kommentare lesen” is a _pseudo-element,_ belonging to a parent element. Pseudo-elements cannot be found programmatically, so  Firefox tells VimFx that the _parent_ element covers the link. And to the right of the parent element there is no link.

I tried injecting this style sheet before looking for markable elements (and removing it when done):

```css
*::before, *::after {
  pointer-events: none !important;
}
```

That does fix the problem (making all pseudo-elements temporarily un-clickable), but made the hints take a bit more than twice as long to appear on screen on Twitter for me, so that solution is not usable in practice.

Back to the drawing board.

**Comment by lydell** [comment]
I did two things here:

1. Since the check for if an element is covered or not can result in false positives, pressing `<c-enter>` in Hints mode now includes potentially covered elements as well. This means that if you find false positives in the future, at least you can use `<c-enter>` as a work-around.

2. If the covering element is a parent to the element we’re checking, the hint marker is attempted to be placed in the center of the element. I figure that’s the most likely spot to be non-covered by pseudo-elements. So don’t be surprised to find the hint marker in the _middle_ of that link in the future.

**Comment by cbaumhardt** [comment]
Thanks a lot for your quick and detailed response as well as the commits! I'll be sure to use `<C-Enter>` in the future and also look in the middle of links if there is no hint at the beginning of them.

Keep up the good work on this great addon :+1:
