### ISSUE TITLE
Questions and Suggestions

### ISSUE THREAD

**Issue by Link-Satonaka** [akhodakivskiy/VimFx#752]
Pentadactyl has been slowly dying over the last year or so, and I'm looking for a simpler replacement; vimperator seems to be working well, but by it's nature, if the devs ever lose interest, it will break within a firefox release or two. VimFx is the most promising replacement, but there are two aspects that really aren't working for me.

#1 modal interface without [enough] visual feedback. I know the icon changes color for insert mode and bypass, but it would be much better if you had a text indicator for *all* modes (excluding perhaps normal).

Why not print the current mode in the bottom right popup you use to show the current keypress and messages?

#2 Filtering through tabs. Currently, there is no interface by which we can navigate tabs. I don't know how you might implement this without breaking your mantra "don't change the interface", but if you could implement a floating window like the chrome extension Vimium, that would be fantastic.

Alternatively, should you know of an existing extension that accomplishes this, or an about:config entry to get the awesome bar work in this way under a specific context, I'd be happy to try that out.

Thanks!

**Comment by Link-Satonaka** [comment]
![2016-06-05-192500_1280x800_scrot](https://cloud.githubusercontent.com/assets/4342746/15808966/4046226e-2b53-11e6-9d74-5c2ecaef30c1.png)
Vimium's floating tab-switching bar

**Comment by lydell** [comment]
> I'm looking for a simpler replacement [for Pentadactyl]

Coming from Pentadactyl, I'm afraid that VimFx will always disappoint you, since it is different by design (as you've also noticed). But since you said _simpler,_ things _might_ work out for you :)

> 1) modal interface without [enough] visual feedback. I know the icon changes color for insert mode and bypass, but it would be much better if you had a text indicator for all modes (excluding perhaps normal).
>
> Why not print the current mode in the bottom right popup you use to show the current keypress and messages?

I think that would annoy many users more than it would help. So for now I suggest writing a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md) and make use of:

- The [`modeDisplayChange`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#the-modedisplaychange-event) event.
- The [`focusTypeChange`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#the-focustypechange-event)
- The `.notify()` method of [Vim object](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#vim-object)s.

You can also you custom [styling](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/styling.md) to some extent to highlight the current mode.

> 2) Filtering through tabs. Currently, there is no interface by which we can navigate tabs. I don't know how you might implement this without breaking your mantra "don't change the interface", but if you could implement a floating window like the chrome extension Vimium, that would be fantastic.
>
> Alternatively, should you know of an existing extension that accomplishes this, or an about:config entry to get the awesome bar work in this way under a specific context, I'd be happy to try that out.

See #420, #540, https://github.com/akhodakivskiy/VimFx/blob/master/documentation/handy-standard-firefox-features.md#the-location-bar and https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#search-bookmarks.

Feel free to ask more questions here if needed.

**Comment by seekM** [comment]
For people who cannot type but use a dictation program to enter text, it would very helpful if one could select open tabs the same way you can select links now - let the characters for selection either be displayed directly in the tabs or inside a floating window like in the screenshot above. The problem is that after having entered `o -> % -> search term` for me there are tabs whose URLs / titles are made from different langauges or other non natural word strings which are not recognizable by the speech engine. Therefore I have to spell or repeatedly dictate the arrow down key to move to the desired tab which is cumbersome. I hope I could shed some light on this from a different perspective. Thanks for the addon which is a great help!

**Comment by lydell** [comment]
@seekM You’re looking for the `zF` command.

**Comment by seekM** [comment]
Oh boy, I guess I should have done more research. Thanks a lot!
