### ISSUE TITLE
Feature requests: Add Zoom in and out key binding

### ISSUE THREAD

**Issue by suzumiyasmith** [akhodakivskiy/VimFx#769]
Feature requests:
shortcut for zoom in and zoom out

Detailed use case example: 
in `normal` mode:
press `zi` ---> webpage zoom in

press `zo` ---> webpage zoom out

In my daily use, when the font of a document in webpage, I have to press Ctrl-- and Ctrl-+ to zoom for a better readding experience. It is annoying especially for laptop keyboard. When reading the local pdf documentation in apvlv, I am using `zi` and `zo` for a better zoom ratio.  
I'd like to pull a requests, but I am not familiar with js. I woud appretiate it if this function could be added.

**Comment by progandy** [comment]
You can add zoom with custom commands, here is an example:
https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#zoom

**Comment by lydell** [comment]
Yes, just like @progandy says the functionality is available as custom commands.

We can't simply include _everything_ in VimFx, even if the commands are very simple. It's important to keep VimFx somwhat small for maintainability. In my opinion, `zi` and `zo` are no improvement over the near-universal `<c-->` and `<c-+>` (in fact, I find it easier to hold the ctrl key and then press `-` or `+` a couple of times, rather than for example `zizizi`). I still understand that other people disagree with this.

See also #261.
