### ISSUE TITLE
follow prev/next on imgur

### ISSUE THREAD

**Issue by lolilolicon** [akhodakivskiy/VimFx#791]
## Steps to reproduce:

1. Add the following to config.js & reload config with `zr`
```
vimfx.addOptionOverrides(
  [ location => location.hostname === 'imgur.com', {
    pattern_attrs: 'class',
    pattern_selector: 'div.next-prev .btn',
    prev_patterns: '.*navPrev.*',
    next_patterns: '.*navNext.*'
  }]
)
```
1. Go to https://imgur.com/gallery/qDsb9 (enable javascript for imgur.com)
1. Press `]`

## Expected result: 

Should navigate to next image, by effectively clicking the `Next Post` button.
I've tried to simulate it with `$('.navNext').click()` in the Web Console, and it works.

## Actual result: 

VimFx notifies `No "Next" link found`.

---
VimFx version: 0.17.4
Firefox version: 48.0
Keyboard language: en-US
Example URL(s): https://imgur.com/gallery/qDsb9

**Comment by lydell** [comment]
Wow! Congratulations on figuring out how to do this by yourself (I didn’t even think this was possible to accomplish through a config file)! You must be some master documentation miner :) :clap: Actually, you are the first person that I see use `vimfx.addOptionOverrides`.

The reason it does not work for you is because you missed a few very subtle details:

The [`vimfx.addOptionOverrides(...rules)`](https://github.com/akhodakivskiy/VimFx/blob/d46849c60b07bc99cc95101669a3d25fcdc2513d/documentation/api.md#vimfxaddoptionoverridesrules) documentation says this:

   > The override is an object whose keys are VimFx pref names and whose values override the pref in question. The values should be formatted as in an [options object].

The [options object] documentation says this:

   > Note that the values are not just simply `vimfx.get(pref)` for the `pref` in question; they are _parsed_ (`parse(vimfx.get(pref))`):
   >
   > - Space-separated prefs are parsed into arrays of strings.
   >
   > - `blacklist` and `{prev,next}_patterns` are parsed into arrays of regular expressions.

The [`pattern_attrs`](https://github.com/akhodakivskiy/VimFx/blob/d46849c60b07bc99cc95101669a3d25fcdc2513d/documentation/options.md#pattern_attrs) documentation says that it is “a space-separated list”. So you need to set it to an array of strings, not just a string.

`{prev,next}_patterns` are mentioned in the second bullet point. The should be arrays of regular expressions, not strings.

[options object]: https://github.com/akhodakivskiy/VimFx/blob/d46849c60b07bc99cc95101669a3d25fcdc2513d/documentation/api.md#options-object

Here is some working code:

```js
vimfx.addOptionOverrides(
  [ location => location.hostname === 'imgur.com', {
    pattern_attrs: ['class'],
    pattern_selector: 'div.next-prev .btn',
    prev_patterns: [/\bnavPrev\b/],
    next_patterns: [/\bnavNext\b/],
  }]
)
```

Look how close you were:

```diff
 vimfx.addOptionOverrides(
   [ location => location.hostname === 'imgur.com', {
-    pattern_attrs: 'class',
+    pattern_attrs: ['class'],
     pattern_selector: 'div.next-prev .btn',
-    prev_patterns: '.*navPrev.*',
-    next_patterns: '.*navNext.*'
+    prev_patterns: [/\bnavPrev\b/],
+    next_patterns: [/\bnavNext\b/],
   }]
 )
```

Now, this post took required me to link to quite a few places i the documentation. Is this a sign that the documentation needs to be improved somewhere? Do you have any suggestions?

**Comment by lolilolicon** [comment]
Thanks for your great answer and patience! Yes yes yes, silly me, of course the parse part is skipped now that we are talking in JavaScript here! Makes sense, haha.

Props to you guys for making all the nice documentation! Even for a new user like me can just poke around a bit and get some shit done... well almost done ;)

As for documentation suggestions, I think the `addOptionOverrides` example can be expanded a bit, to include for example some of those options I stumbled upon here. Examples are great!

---
One more question.

I find in this case `zr` doesn't actually apply my fixes. I had to disable then enable VimFx. I suppose the problem is that option overrides are appended to existing ones when I do `zr`. Is there a way to remove all option overrides in config.js?

**Comment by lydell** [comment]
Thanks, I’ll try to improve the `addOptionOverrides` example!

Regarding, `zr` not applying your fixes. Old overrides are supposed to be removed when you press `zr` (there’s even a test for that!). I think that you have to reload the page. optionOverrides are triggered based on URLs – and only when they change, or when VimFx starts up.

**Comment by lolilolicon** [comment]
OK, thanks for the clarification. Seems to work now, not sure what happened back then. Thanks :)
