### ISSUE TITLE
"User" preferences should NEVER be overriden

### ISSUE THREAD

**Issue by amn** [akhodakivskiy/VimFx#798]
After VimFx somehow automatically being updated to 0.18.0, I can see that the "follow link in new [foreground] tab" is now bound to another key combination than its earlier "gf" to which my fingers got used to.

*puts on pedant glasses*

Changing what amounts to a learned user preference is a UX no-no. I understand that there were probably *all kinds of valid* reasons for changing the default, but since there is no effective separation of "user" preferences from defaults, after using VimFx for a month, the preference becomes *mine* and is no longer considered *default* -- i.e. you can't just change it with an update. I finally went to VimFx preferences after `gf` not working for a day, only to discover the binding has changed! Without me changing it!

I suppose a solution would be to keep two copies of bindings -- a default set and the user or overriden set. Much like Firefox does this in `about:config`. That way, you can change things around with updates that apply to default set, with the user not encountering the system switching their preference from under them, so to speak.

I know a lot of software pays no mind to such things, and VimFx is not like the sole offender here, but since I like it a lot, I care and I hope this does not fall on deaf ears :)

Should probably finish up with a thanks for a very useful addon!

VimFx version: 0.18.0
Firefox version: 47.0.1
OS: Windows 10 x86-64
Keyboard language: US International
Worked before: Yes?
Example URL(s): N/A

**Comment by lydell** [comment]
First: Sorry for breaking your workflow. Doing so always sucks.

I really don't like changing default shortcuts, so that's very rarely done (last time was the 0.5.17 → 0.6.0 update). This time I went through _all_ shortcuts and really asked myself if it would be worth changing them. Something _had_ to be done with the `f` commands to be able to go forward in the future. Now, the defaults should be ready for 1.0.0, after which no breaking changes will happen until 2.0.0, and the major version number won't be bumped lightly.

Regarding add-on updates, that's a pretty sucky part of the Firefox add-on system, in my opinion. Fully automatic and silent updates is great for non-breaking bugfix releases, but annoying in other cases. I think Firefox should acually _use_ the add-on version numbers somehow to tell if the user has to know before updating. Or at least notify you that add-ons have been updated.

Some add-on developers resort to opening a tab with information about the update the first time the add-on is started after an update. However, lots of users hate that, forcing the developer to add an option to turn it off. I'm not sure this is the way to go.

Myself, I've long ago switched automatic add-on updates off and manually visit the Add-ons Manager a few times a month or so to check for updates and read changelogs before updating.

I won't lock down any VimFx prefs the way you describe. Some prefs make sense to be automatically updated. Not even just locking down the shortcut prefs would be a good idea, I think, because there are lots of people who only use a small subset of VimFx. When they learn about a new command that they've never used before, it would be very confusing if the documentation and the user's setup would be out of sync. "Why is the documentation telling me to press `gC` over and over again, while it seems to be `zr`?"

Here's what you can do. Choose one of these:

1. Go into every text input in VimFx's settings page in the Add-ons Manager. Type in a random character, then backspace it out again. The pref for that option will now be marked as "user set" in about:config (even if its value happens to be equal to the default). Now, changes to VimFx's defaults cannot affect you. (You can also do this via about:config). This is simply how Firefox's prefs system works.

2. Write a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md) and explicitly pin down the settings you want.

**Comment by amn** [comment]
Thank you for thorough explanation, it seems somehow part of the solution is already there -- I am referring to the fact that VimFx settings are stored much the same way the rest of Firefox' settings are.

I did what you suggested in #1, the funny thing is that typing in say, "et" as my new preferred shortcut for opening a link in foreground tab  (same as VimFx default, but now that it is the new default shortcut, I thought I will commit myself to it as my new preference), Firefox thinks it is the default just because it matches the default value. That's probably not how it should work -- the point is that you should be able to pin the setting down with your own preference, even if it *matches* the default. So that when the default is changed upstream, your preference still remains.

Anyway, it seems I have the option of using a configuration file, so that should do it. I wish anyhow that the about:config worked the way I described above.

**Comment by lydell** [comment]
Thanks for letting me know that the prefs system does not work like I described in 1). I’m 99% sure it used to, but now when I tried it you’re right – the prefs are not marked as “user set”. One thing you _can_ do, though, is to add a space at the end of all shortcuts.
