### ISSUE TITLE
Access content in config.js vs frame.js

### ISSUE THREAD

**Issue by lolilolicon** [akhodakivskiy/VimFx#800]
I feel pretty stupid asking this, but I'm confused...

```js
// config.js

vimfx.addCommand({
  name: "foo",
  description: "bar",
}, ({vim}) => {
  vimfx.send(vim, "getSelection", null, selection => {
    console.log(">>>", selection);
  });
});
```
```js
// frame.js

vimfx.listen("getSelection", (data, callback) => {
  let selection = content.getSelection().toString();
  callback(selection);
});
```
v.s. simply
```js
// config.js

vimfx.addCommand({
  name: "foo",
  description: "bar",
}, ({vim}) => {
  let selection = vim.window.content.getSelection().toString();
  console.log(">>>", selection);
});
```

The documentation seems to suggest `content` should be dealt with in `frame.js`, but in `config.js` once we get the `vim` object, we have access to `vim.window.content`.
Is there any case in which these two `content`s aren't the same?
Is there any reason why one should do it in `frame.js`?

**Comment by lydell** [comment]
The config.js/frame.js split is due to [multi-process Firefox (a.k.a. Electrolysis and e10s)](https://wiki.mozilla.org/Electrolysis).

`vim.window.content` won't work in multi-process Firefox. It's there just for compatibility with older add-ons (until Mozilla finally decides to kill it completely).

**Comment by lolilolicon** [comment]
Just what I was suspecting. Good to know, thanks for the clarification.
