### ISSUE TITLE
No image element context menu 

### ISSUE THREAD

**Issue by gregBurgers** [akhodakivskiy/VimFx#804]
Steps to reproduce:

1. Get focus of an image element. For full example's sake, image should NOT be hyperlinked. I could do this by pressing: ef (element focus), \<c-enter\> to select other elements (because ef doesn't show labels for images by themselves), select image
2. Open context menu by pressing \<menu\> 

Expected result: 
When using a mouse to right click an image element I get a full list of image relevant context menu items like: reload image, view image, copy image, copy image location, view image info + other items added by addons (Umatrix: block element, Policeman: Blocked Image (with submenu items))

Actual result: 
I don't believe the image element gets selected.
For an image by itself:
The context menu is the generic context menu when right-clicking on a blank space on a page. It does not appear next to the selected element, it appears in the top left corner of the screen

Alternatively, when selecting  a hyperlinked image:
The context menu is only populated by hyperlink-specific items

i don't know if this is a bug or a feature request but here is a 'detailed use case example':

- A user wants to use vim to copy an image, or copy image location

- in my case I use the addon Policeman to block all images from being loaded, and it adds a context-item when you right click on an image to allow one to load the selected blocked image

VimFx version: 0.18.1
Firefox version: 48.0
OS: Linux, openSUSE
Keyboard language: en-US
Worked before: /
Example URL(s): vim.org

**Comment by lydell** [comment]
Thanks for your detailed report!

The problem is that images are not keyboard focusable (you can't press `<tab>` to focus one). VimFx can currently only focus keyboard focusable elements (that's why `ef` doesn't give hints for images).

Still, opening the context menu for images is, as you describe, useful.

Perhaps we should try to find a way to programmatically trigger the context menu. Then we could add a new hints command – `ec` (c as in context menu), perhaps – that let's you open the context menu for images, links and text inputs.
