### ISSUE TITLE
Find mode highlighting all matches (a/) does not highlight if find bar is closed too quickly

### ISSUE THREAD

**Issue by lotheac** [akhodakivskiy/VimFx#816]
Steps to reproduce:

1. Open http://pubs.opengroup.org/onlinepubs/9699919799/functions/close.html
2. Type "a/close", without hitting return. Observe correct highlighting of all
matches.
3. Type "a/c\<Return\>" quickly. If I wait for a bit before hitting return, the
highlighting corrects itself.

Expected result: 

Occurrences of 'c' are highlighted on the page and n/N can be used to move
between them.

Actual result: 

Occurrences of 'close' are highlighted on the page, but n/N move between
matches of 'c'.

VimFx version: 0.19.1
Firefox version: 49.0.1
OS: OpenBSD 6.0-CURRENT
Keyboard language: Finnish
Worked before: Don't know, just installed VimFx.
Example URL(s): http://pubs.opengroup.org/onlinepubs/9699919799/functions/close.html

**Comment by lydell** [comment]
Hi! Thanks for your report!

I have trouble following your steps. In step 3, I end up typing the text "a/c" in the findbar (after the text "close", which I typed in step 2), but I'm pretty sure that's not what you mean, so I tried hitting return at the end of step 2 (even though you said I shouldn't!) When the find bar is closed, all highlighting goes away. Then, after I have typed `a/c<enter>` as quickly as I can, `n` and `N` move between occurrences of 'c', as expected. Sometimes, all occurrences of 'c' get highlighted after a second or so. (That sounds like a Firefox bug.)

I also tried doing this with `<c-f>` (the standard Firefox shortcut for opening the find bar) instead of (`a/`). First I opened the find bar with `<c-f>` and clicked the "Highlight all" button. After that, the find bar remembers your "Highlight all choice". Then I tried your steps again, but with `<c-f>` instead of `a/`. As far as I can tell, the results were exactly the same.

VimFx version: 0.19.1
Firefox version: 51.0a2
OS: Ubuntu 16.04

**Comment by lotheac** [comment]
On Wed, Sep 28 2016 08:27:25 -0700, Simon Lydell wrote:
> I have trouble following your steps. In step 3, I end up typing the text "a/c" in the findbar (after the text "close", which I typed in step 2), but I'm pretty sure that's not what you mean, so I tried hitting return at the end of step 2 (even though you said I shouldn't!)

Sorry, I was unclear here. Step 2 should read "hit return after one
second or so", not "without hitting return".

> When the find bar is closed, all highlighting goes away. Then, after I have typed `a/c<enter>` as quickly as I can, `n` and `N` move between occurrences of 'c', as expected. Sometimes, all occurrences of 'c' get highlighted after a second or so. (That sounds like a Firefox bug.)
> 
> I also tried doing this with `<c-f>` (the standard Firefox shortcut for opening the find bar) instead of (`a/`). First I opened the find bar with `<c-f>` and clicked the "Highlight all" button. After that, the find bar remembers your "Highlight all choice". Then I tried your steps again, but with `<c-f>` instead of `a/`. As far as I can tell, the results were exactly the same.

Hmm, you're right, it's likely this is a Firefox bug. I've been using
pentadactyl up until now, and I only just discovered this after
switching to VimFx so I made an invalid assumption. Thanks for the
input.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by lydell** [comment]
Ok, if you think it's a Firefox bug then I'm closing this.

**Comment by lotheac** [comment]
On Wed, Sep 28 2016 08:45:17 -0700, Simon Lydell wrote:
> Ok, if you think it's a Firefox bug then I'm closing this.

A further data point now that I had time to try to repro this on vanilla
Firefox: it's not really a problem there because hitting return does not
close the find bar.

I realize that it still is a Firefox bug that the highlighting doesn't
happen if you close the find bar too fast, but it's harder to do with
plain Firefox (ie. you have to hit Esc instead). I should probably
report it upstream in any case.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by lotheac** [comment]
On Thu, Sep 29 2016 10:39:04 +0300, Lauri Tirkkonen wrote:
> I should probably report it upstream in any case.

Or maybe I won't - the new Find bar in Firefox 50 works differently in
that it removes the highlighted matches when it's closed (with
findbar.modalHighlight=false, the default in just-downloaded Developer
edition). Now I'm unsure where the correct place to fix this is -- it's
entirely reasonable for Firefox to remove the highlights when the find
bar is closed, but not closing it doesn't really fit in a vi-style
workflow.

Thoughts?

-- 
Lauri Tirkkonen | lotheac @ IRCnet
