### ISSUE TITLE
How to stop VimFx from autofocusing on url field in new tabs?

### ISSUE THREAD

**Issue by mzbab88** [akhodakivskiy/VimFx#819]
I use [ and ] to go to the next previous tabs. It works fine, but it stubles on empty tabs, and starts typing the url instead. So I have to press escape every time that happens.

Can you show me where in the code VimFx sets that autofocus up? Maybe I'll fix it myself, if I'm lucky.

**Comment by lydell** [comment]
> Can you show me where in the code VimFx sets that autofocus up?

VimFx doesn't. Firefox does. For the `t` command, VimFx simply calls a global function called `BrowserOpenTab`. That works like the Firefox default shortcut `<c-t>`, or clicking the new tab button.

> Maybe I'll fix it myself

There's nothing to fix, because things are working as intended. Why open a new tab if you don't want to go somewhere in it? :) Anyway, here's a custom command for you (add it to a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md)):

```js
let {commands} = vimfx.modes.normal

vimfx.addCommand({
  name: 'tab_new_with_unfocused_location_bar',
  category: 'tabs',
  description: 'New tab with unfocused location bar',
  order: commands.tab_new.order + 1,
}, (args) => {
  commands.tab_new.run(args)
  commands.esc.run(args)
})
```

> stubles [sic] on empty tabs, and starts typing the url instead.

I guess that you mean "I stumble on tabs where the location bar (or any text input for that matter) happens to be focused". Perhaps the above command will help you, perhaps not. Another way is to add shortcuts that will _always_ trigger, such as `<force><a-j>` (for `J`) and `<force><a-k>` (for `K`).
