### ISSUE TITLE
Clicking places caret

### ISSUE THREAD

**Issue by elvis-sik** [akhodakivskiy/VimFx#821]
- [x] I've searched for DUPLICATES – also closed issues
- [x] I've looked at the change log:
- [x] I've provided the below details:

VimFx version: 0.20.0
Firefox version: 49.0.1
OS:  Arch
Keyboard language:  br-abnt2
Example URL (if any): any, really

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [x] Somehting else

I am not sure if the behavior that I will describe is a new feature or something.  It didn't happen until recently, and I neither remember changing the configurations nor can find anything that seems related in them.

When I click on an element on a page, the caret is placed there. This makes navigation painful, because if I click on, say, a radio button, and then try to  navigate with `jk`, the caret will move, and this doesn't necessarily result in smooth navigation.

Is this expected? Is there a way to modify this behavior?

**Comment by lydell** [comment]
When you enter VimFx's Caret mode (for example by typing `v<hint>`), VimFx temporarily enables [Firefox’s own Caret mode](http://kb.mozillazine.org/Accessibility_features_of_Firefox#Allow_text_to_be_selected_with_the_keyboard). When you exit VimFx's Caret mode, VimFx makes sure to disable Firefox's caret mode again – _unless_ VimFx detected that you had Caret mode enabled even before VimFx entered its own Caret mode. (Some (few?) people like to have it on always.)

I think that you entered VimFx's Caret mode some time, and perhaps closed Firefox while in that mode or something, so that VimFx never got a chance to disable it again, leaving you with it always on.

The quick fix is to press `<f7>` to disable it.

I think that we should make VimFx _always_ disable Firefox's Caret mode, and add an advanced option for users who actually want it to be on always.

**Comment by elvis-sik** [comment]
Since this can happen:

> I think that you entered VimFx's Caret mode some time, and perhaps closed Firefox while in that mode or something, so that VimFx never got a chance to disable it again, leaving you with it always on.

I personally feel this is a good idea:

> I think that we should make VimFx always disable Firefox's Caret mode, and add an advanced option for users who actually want it to be on always.

Anyway, thanks for the hint, you diagnosed it correctly.
