### ISSUE TITLE
Default mapping:  <CTRL>-[  =>  exit

### ISSUE THREAD

**Issue by PoppinTags** [akhodakivskiy/VimFx#823]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.0
Firefox version: 49.0
OS: Ubuntu 16.04
Keyboard language: en-US
Example URL (if any): 

This is … (pick one!)

- [x] A feature request
  - [x] I've given a **detailed** _example_ below

Thank you for developing this plugin. It's fast and works very well. The only issue I'm having looks like a reoccurring theme: the default mapping of `<ctrl>-[` to exit (as an alternative to `<escape>`).

It's referenced in these previous issues: #113, #347, #501, which are all closed, but the mapping doesn't work. There is the option to roll a custom config, but it seems like overkill to add a single hotkey for otherwise intuitive defaults.

It would be great if by default `<ctrl>-[` would trigger exit, escaping find and browse menus, returning to normal mode.

**Comment by lydell** [comment]
Thanks for your detailed report!

- I’ve improved the documentation: For people who find this while searching: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/questions-and-answers.md#how-do-i-re-map-escape-which-blurs-text-inputs

- I’ve made sure that trying to set a mapping to for example `<ctrl>-[` (instead of the correct `<c-[>`), an error is shown telling you how to fix it.

- `<c-[>` won’t be added by default.
