### ISSUE TITLE
Switch betwen tab in a similar way than to follow links

### ISSUE THREAD

**Issue by gagarine** [akhodakivskiy/VimFx#831]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.30
Firefox version: 49
OS: macOS
Keyboard language: CH
Example URL (if any): 

This is 
- [x] A feature request
  - [x] I've given a **detailed** _example_ below

In Firefox you can switch between tab using CMD-# but you can only switch from tab 1 to 9.

It would be cool to implement a feature like for the link (f and then complete with letter and then enter) but for the tab. Perhaps for the tab it would be easier to just use number. But I have to say using letter would have the advantage to be more "stable" (the letters combination fr one tab will not change, even if you change your tab order).

So I imagine it like that:
- Press t (I know this is already used, but in my opinion new tab should be nt, new windows nw, new private windows npw, ...)
- Tab's letter combination get highlighted
- Press a key letter
- Tab starting with this letter stay visible, the others get hidden (or get a lower width)
- Press other key if needed until the tab you want is selected
- Press enter to get the focus (or perhaps tab can switch instantly)

**Comment by lydell** [comment]
Does the `eb` command do what you want?

**Comment by gagarine** [comment]
OMG! Yes it's already very good :). The only things, is you can only select visible tabs and letters you have to type to select an element changes if you close/open tabs. But already a life changer.

**Comment by lydell** [comment]
So, what do you suggest?

**Comment by progandy** [comment]
Maybe a window mode similar to the help screen would work that displays all tabs with a search box.

I don't miss it though, since I am using the Tab Group extensions and its search function. (Ctrl-Shift-E, then Ctrl-F)

**Comment by gagarine** [comment]
Tab highlights is great, you can quickly move to a visible tab:
![screen shot 2016-11-04 at 21 03 16](https://cloud.githubusercontent.com/assets/164074/20024869/9ff26b92-a2e9-11e6-8fb2-7c217e181d6b.png)

Limitations:
1)  you can't switch to non-visible tabs
2) letter change, you can't remember a tab shortcut
3) others?

## you can't switch to non-visible tabs
What do you think of a sidebar similar to the tab's drop-down menu?:
![screen shot 2016-11-04 at 21 02 57](https://cloud.githubusercontent.com/assets/164074/20024868/9e84c5f2-a2e9-11e6-8ce9-b7b007840808.png)

I think we can mix both concepts, keeping the tab highlights -> it's useful if you just see a tab on the top of the windows and want to switch to it.

Show all tabs stacked in a drop-down or like tab group.

## letter change, you can't remember a tab shortcut
This one is easier perhaps. We can use the title of the tab to generate the sequence.  For example, the first letter of each word. Or the first letter of the domain name and then the first different letters of the title of every other tabs.

This can be powerful if we hide tab when we start typing the shortcut. For example, I know I want to go back to a Wikipedia page, so I first type w and then type the second letter of the tabs than are still there.

Say that perhaps the easiest would be to create an integration with Tab group.

What do you think?

**Comment by lydell** [comment]
Thank you for the nice feedback! That’s very much appreciated.

> 1) you can't switch to non-visible tabs

Thanks! That’s a bug. I’ve pushed a commit so that the `eb` command now recognizes the scroll arrows on the tab bar, so that you can scroll to the left and right until the tab you’re looking for becomes visible.

> 2) letter change, you can't remember a tab shortcut

That’s a good point. I use the `eb` command for two things exclusively: Clicking tabs and clicking stuff in the devtools. So it might be worth changing the hint generation to favor the tabs, and make the hints for the tabs stable. I’ll have to think about that.

> Tab Group extension

I cannot find any add-on called “Tab Group” on [addons.mozilla.org](https://addons.mozilla.org/). Can you post a link to it?

When you talk about integrating with it, do you mean making a custom command to trigger some feature it provides?

---

Finally, it sounds like what you want is described here:

https://github.com/akhodakivskiy/VimFx/blob/master/documentation/handy-standard-firefox-features.md#the-location-bar

**Comment by progandy** [comment]
> I cannot find any add-on called “Tab Group” on addons.mozilla.org. Can you post a link to it?

I use this one: https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/ If you only want to search for tabs, then it is overkill. Since I use this addon I totally forgot about the tab search operator for the location bar.

> Say that perhaps the easiest would be to create an integration with Tab group.

Not really, only if you want to fully support that addon and I think that is unnecessary. It would be much easier to implement your own searchable tab list I think and with the ```%``` in the location bar even that is unnecessary.

**Comment by lydell** [comment]
I forgot to mention: If you regularly have more tabs than can fit horizontally in the window, I really recommend using a vertical tab bar. I have used a vertical tab bar for years, and I love it. There are plenty of alternatives for doing so.

**Comment by gagarine** [comment]
Very good, using the % with location bar will suit my need. I'm going to use https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#search-bookmarks--search-open-tabs to quickly jump in.

**Comment by lydell** [comment]
I've updated the custom command to also automatically open the autocomplete popup. (You might also be interested in the commit mentioned just above this comment.)

In the next version, `eb` will also use consistent hints for the tabs. They're not based on the tab titles, but the first (visible) tab always gets the same hint, the second tab always get the same hint and so on.
