### ISSUE TITLE
TypeError: 'querySelectorAll' called on an object that does not implement interface Document. (Need general JavaScript help for a config file.)

### ISSUE THREAD

**Issue by FichteFoll** [akhodakivskiy/VimFx#841]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.4
Firefox version: 50.0
OS: Windows 7
Keyboard language: irrelevant
Example URL (if any): irrelevant

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else (config files)

Steps to reproduce:

1) `config.js`
```
vimfx.addCommand({
  name: 'find_something_in_document',
  description: 'Test',
}, ({vim}) => {
  vimfx.send(vim, "query_selector_test");
});
vimfx.set("custom.mode.normal.find_something_in_document", ",t");
```
2) `frame.js`
```
vimfx.listen("query_selector_test", (data, callback) => {
    console.log(content, content.document);
    const $$ = content.document.querySelectorAll;
    $$("table.wikitable tr:nth-of-type(1) td:nth-of-type(2)").forEach((e) => {
        console.log(e);
    });
});
``` 
3) open any page and press `,t`

Expected result: Found elements are printed on the console.

Actual result: 
```
Window → https://github.com/akhodakivskiy/VimFx/issues/841 HTMLDocument → https://github.com/akhodakivskiy/VimFx/issues/841
TypeError: 'querySelectorAll' called on an object that does not implement interface Document.
```

**Comment by FichteFoll** [comment]
Inspecting the printed HTMLDocument does indeed reveal that it doesn't implement querySelector or querySelectorAll, although the docs mention that [HTMLDocument](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDocument) provides a superset of [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document), which lists these.

**Comment by lydell** [comment]
If you change the following line:

```js
const $$ = content.document.querySelectorAll;
```

... to:

```js
const $$ = (...args) => Array.from(content.document.querySelectorAll(...args))
```

... things should work out for you.

Feel free to ask more questions in this issue if needed! :)

**Comment by FichteFoll** [comment]
Thanks, that works ...

... but why?

**Comment by lydell** [comment]
The `querySelectorAll` method uses `this` inside. In JavaScript, the value of `this` generally depends on **how you call a function/method.** When you run `content.document.querySelectorAll(...)`, `this` is set to `content.document`. But if you run `const {querySelectorAll} = content.document; querySelectorAll(...)`, JavaScript doesn't know what to set `this` to, so it defaults to setting `this` to the global object (!). So that's basically like running `content.document.querySelectorAll.call(global, ...)` (assuming the global object is available as `global`). And the global object does not implement the interface Document.

Secondly, `querySelectorAll` does not return an Array, but an Array-like [NodeList](https://developer.mozilla.org/en/docs/Web/API/NodeList), which does not have the `forEach` method. That's why we use `Array.from` to convert to an Array.
