### ISSUE TITLE
Missing hint markers for some of elements on Trello boards

### ISSUE THREAD

**Issue by Tunous** [akhodakivskiy/VimFx#844]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.4
Firefox version: 50.0.2
OS: Arch Linux
Keyboard language: pl
Example URL (if any): https://trello.com/b/LeuoXpLi/demo, https://trello.com/c/mJViYjbZ

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [x] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [ ] Something else

Steps to reproduce:

1. Go to https://trello.com/b/LeuoXpLi/demo
2. Press `f`

Expected result: There should be hint marker for both list titles.

Actual result: There is no hint marker for list titles.

1. Go to https://trello.com/c/mJViYjbZ
2. Press `f`

Expected result: There should be hint marker for checklist items and checkboxes.

Actual result: There is no hint marker for checklist items and checkboxes.

___

**Additional notes:** It might be required to use Trello account and create own board to get access to editing described elements. The issue happens on all Trello boards with edit access.

**Comment by lydell** [comment]
The only way to target those elements is to special-case them. Trello does not provide any general information that those elements are clickable.

Workaround for editing title: Open the card. When open, it it possible to edit the title using VimFx.

Unless there turns out to be a high demand for these special-cases, I won't add them to VimFx. Instead I suggest:

1. Use the workaround.
2. Contact Trello and ask them to improve their accessibility.
3. Add the following to a [config file](https://github.com/akhodakivskiy/VimFx/blob/c06315c2dd6258af28dc99cd5ba1f653180c681e/documentation/config-file.md):

```js
// frame.js
vimfx.setHintMatcher((id, element, type) => {
  if (
    id === 'normal' &&
    element.classList &&
    (
      element.classList.contains('js-editing-target') ||
      element.classList.contains('checklist-item-checkbox')
    )
  ) {
    return 'clickable'
  }

  return type
})
```

**Comment by Tunous** [comment]
Thank you for the quick reply. I've contacted Trello about the issue and will comment with information once I receive response.

**Comment by Tunous** [comment]
Information from reply:

> I'll go ahead and will pass this on to the team so they can take a look and improve how that's being handled by Trello. I don't have an ETA on when those changes will be made, but I'll make sure to let the team know that this is causing problems for accessibility and this specific extension.
