### ISSUE TITLE
 VimFx v0.24.0 is not compatible with WaterFox

### ISSUE THREAD

**Issue by archerhush** [akhodakivskiy/VimFx#950]
As title states, I've been running VimFx v0.23.3 and it was working under `waterfox-current` (Debian GNU/Linux bullseye/sid x86_64).
VimFx v0.24.0 doesn't work anymore, though. I am able to use it under (like getting hints by pressing `f` under `about:addons`)- Could you make it compatible with this FX fork? And I still have the problem I can't pull up my copy of LegacyFox, that's why I'm using WaterFox.

**Comment by archerhush** [comment]
Okay, I think it's a bug. I've tried resetting all configs (basically I was using a different hint charset, `FJDKSLAGHRUEIWONC MV`... this config is taken from the v0.23.3 one instead of the default lower charset). Then I've set it to `FJDKSLAGHRUEIWONC MV` once again and it started working again.

**Comment by girst** [comment]
is it possible that a browser restart fixed the issue, and that the 
charset was a red herring? vimfx sometimes breaks on update (no clue 
where exactly, otherwise i'd've fixed it).

if that's not the case, and you still have your old config, I'd love to 
look at them (any vimfx config and frame scripts, about:config prefs 
mentioning vimfx).

regarding waterfox: i do intend to support firefox-esr, so i'm happy to 
make some accomodations for the waterfox that tracks upstream. no 
promises on anything, of course. ;-)

i'll look into it.

**Comment by archerhush** [comment]
@girst I've downgraded to VimFx v0.23.3. I suspect there is something like this reproducible for Firefox-ESR, can you look into it (after looking the bug with WaterFox?).

**Comment by girst** [comment]
it looks like i can't reproduce this on my end. here are my attemted 
str:
1. download waterfox 2020.06 tarball and start it
2. install vimfx 0.23.3, change charset to uppercase
3. upgrade to 0.24.0
4. re-do with mozilla esr 68 tarball

everything still works for me, before and after restarting the browser.

can you please do the following:
0. verify your current setup (waterfox+.23.3 i believe) works
1. open the browsr console with ctrl-shift-j and clear it
2. install vimfx 0.24.0 and watch the console
3. check if it is now broken
4. if it is broken, restart the browser (ctrl-alt-r in the browser 
console)
5. check if it works again

and send me the output of the browser console please. note that the 
browser console is different to the devtools-console.

**Comment by archerhush** [comment]
@girst restarting the browser doesn't fix anything.
Also ctr+shift+j browser console doesn't show anything after I clear and I install vimfx.xpi from releases into this repo.
Try to restart the browser (waterfox-current), press `f` and start "hinting", like on facebook or others. I can do it just in pages like `about:addons`, idk why.

**Comment by girst** [comment]
can you show me the messages that show up in the browser console 
directly after a browser restart?

**Comment by archerhush** [comment]
@girst [https://i.imgur.com/vpmDkE3.png](here)

**Comment by girst** [comment]
hmmm, no errors there either. do you have another machine (or vm) where 
you can try to reproduce this? i tried it again (freshly downloaded 
waterfox in a fedora30 vm) and it works there.

**Comment by archerhush** [comment]
I have i3wm (i3-gaps), debian bullseye/sid x86_64... like I've said in the past issue discussion, you can just download an old version and just dist-upgrade to the most recent one. it's pretty weird it's just me having these problems, and not you.

**Comment by girst** [comment]
On Mon, Jun 15, 2020 at 04:12:25PM -0700, archerhush wrote:
>like I've said in the past issue discussion, you can just download an 
>old version and  just dist-upgrade to the most recent one.

you're asking me to invest a lot of time into debugging a problem that 
is most likely with your setup, not vimfx. i doubt that me setting up a 
debian vm will help with that.

>it's pretty weird it's just me having these problems, and not you.

and that's why i need *you* to try this on a different computer or 
virtual machine.

**Comment by girst** [comment]
ping, @archerhush: have you tried to reproduce this on a second computer/virtual machine?

**Comment by girst** [comment]
On Wed, Aug 05, 2020 at 05:22:21AM -0700, archerhush wrote:
> the `af` combination (open multiple links) doesn't work 
>properly.
>I'm searching for multiple text link hints and it works just once (I 
>can't search for text link hints more than one time).

can reproduce in esr68. given that 68 is on it's way out, i don't feel 
inclined fixing it, but will (gladly) accept a patch.

>Also, regarding `eb` keys combination why can't I click browser 
>elements by typing text? Is this a missing feature or a bug? If it's a 

missing feature. but i can't see the point in it, since no ui element 
has text visible (except tabs, but there's alt+[1-9] for that).
