### ISSUE TITLE
VimFX highlights non-interacterable/useless elements.

### ISSUE THREAD

**Issue by monomachos** [akhodakivskiy/VimFx#954]
I've run into a problem element while experimenting with highlighting. Pay attention to the space with the hint marked **MJ**.
Highlighting by pressing **f**:
![1](https://user-images.githubusercontent.com/59909838/101236512-ae235200-3686-11eb-9ff6-59d4f9858f33.png)
versus highlight by pressing **F**:
![2](https://user-images.githubusercontent.com/59909838/101236520-c004f500-3686-11eb-9695-8aeac4bdf6cb.png)
In the next screen I started typing out the word "advantage" (I use all capital letters for hints), but VimFX does not automatically redirect me because it can't decide between those two hints. Strange!
![3](https://user-images.githubusercontent.com/59909838/101236529-e460d180-3686-11eb-8059-f171adb8c22e.png)
I can't open a context menu on that hint with **ec**:
![4](https://user-images.githubusercontent.com/59909838/101236614-6e109f00-3687-11eb-8193-d66e066e8266.png)
I can't focus on it with **ef**:
![5](https://user-images.githubusercontent.com/59909838/101236638-bdef6600-3687-11eb-9121-1b7a0a9768a4.png)
It doesn't have any text I could copy with **yf**:
![6](https://user-images.githubusercontent.com/59909838/101236648-db243480-3687-11eb-90da-dff3a525fa1e.png)
So why is VimFX even bothering to show me it? It cannot be filtered out of view so VimFX does not redirect me to the proper hint.

You can find the element on old.reddit.com.

**Comment by girst** [comment]
the container `<div>` has an onclick handler, hence the `f` hint. i guess that since the text you're typing is both within the `<a>` and indirectly inside the `<div>`, the hint won't go away.

link hinting is based on heuristics, so it can never be perfiect. feel free to poke around in lib/commands-frame.coffee or lib/markable-elements.coffee and send a PR, if you have improvements.

**Comment by monomachos** [comment]
The div has an attribute onclick="click_thing(this)". Removing that attribute removes the hint.

Relevant code:
https://github.com/akhodakivskiy/VimFx/blob/a2f1c749168ef67f1122f60af1eef5369e16ed44/extension/lib/commands-frame.coffee#L273-L286

So how do we distinguish between this element and an actual clickable element?

**Comment by girst** [comment]
On Sat, Dec 05, 2020 at 11:07:45AM -0800, monomachos wrote:
>So how do we distinguish between this element and an actual clickable 
>element?

the problem is that this can't really be generalized. the inner element 
isn't covering the outer element fully (this case is already handled by 
vimfx). in the case of old.reddit, the outer element is "useless", but 
on some other website it's conceivable that a similar arrangement does 
something useful.

i'd suggest writing a userscript to patch this locally.
