### ISSUE TITLE
Vimfx can't be installed on newer firefox (and firefox-nightly) but works on debugging mode

### ISSUE THREAD

**Issue by ZWindL** [akhodakivskiy/VimFx#956]
Hi, thanks for the amazing extension, just noticed it's still alive these days. Really miss it.

I found that vimfx can't be installed but works perfectly under debugging mode.

OS: ArchLinux
Browser: Firefox 85 & Firefox 83
Legacyfox: 2.3, both installed for v85 and v83

Related issue #947 

Here's the log output in C-shift-j console when installing it:

![Screenshot_20201211_154622](https://user-images.githubusercontent.com/5116996/101876787-f92def80-3bc7-11eb-8e91-2c228068d65c.png)

it refers to this line of code:
```js
 try {
      await this.loadManifest(this.file);
    } catch ([error, message]) {
      logger.warn("Invalid XPI", message);
      this.state = AddonManager.STATE_DOWNLOAD_FAILED;
      this.error = error;
```

so I thought that maybe because the vimfx doesn't have a valid manifest.json file.

I tried to write one on my own but failed.

**Comment by girst** [comment]
I just tried installing vimfx on today's nightly build, and it works for 
me. the code snippet you've posted is the path taken by webextensions, 
firefox should never call this part when installing vimfx. so i suspect 
that legacyfox isn't loaded properly.

here's what i need you to do:

- please check that resource://legacy/ gives you a list of three .jsm 
   files (and that they aren't empty)

- open about:config and type 'general.config'. post results.

- open about:support and search for 'application binary'. go to this 
   directory and verify that config.js, legacy.manifest, legacy/*.jsm and
   defaults/pref/config-prefs.js are present.

- hit f12 to open devtools, then f1 to open settings and enable both 
   "enable browser chrome and add-on debugging toolboxes" and "enable
   remote debugging". then open the browser console (ctrl-shift-j) again.
   it will now allow you to run javascript code with the highest
   privilege level. issue the following:
     ({AddonManagerPrivate} = Cu.import("resource://gre/modules/AddonManager.jsm"))
     AddonManagerPrivate.externalExtensionLoaders
   and expand the Map object and its 'entries' subobject. you should see
   a "bootstrap -> Object {...}" entry there.

- where did you install firefox/nightly from (arch repo, aur, 
   mozilla,...)? can you reproduce it with the binaries from
   'https://mozilla.org/nightly'?

- your log shows a lot of other extensions. please create a new profile 
   (firefox --ProfileManager) and try installing and the above steps in
   that one too.

for some backgorund info, in case you're interested:

we can't use a manifest.json, that's only for webextensions and won't 
allow vimfx to run with the privileges it needs. legacyfox ships some of 
the old extension code (the bootstraploader), and installs a hook that 
runs it if a non-webextension (with an install.rdf) is found. so as long 
as LF is properly installed, we won't need a manifest.json (which 
wouldn't work anyways). so the fact that your firefox tried to use the 
manifest.json path instead of the install.rdf one suggests to me that 
legacyfox/bootstraploader isn't installed properly.

**Comment by ZWindL** [comment]
@girst Thanks for the help, and sorry, I'm too busy these days.

The pre-build package from 'https://mozilla.org/nightly' does working, and I'm currently using package firefox-nightly-en-us from archinuxcn repo (I think its identically with the aur version), it's not working even with new profile.

I bypassed install errors by installing vimfx from mozilla-version + my current profile.

Please don't close this issue, I will try rest of the steps you metioned before and find out why it won't work with aur package.

Thank you Grist.

**Comment by girst** [comment]
No worries, I've marked the ticket as 'waiting'. I had a quick look at 
the PKGBUILD and it looks like it is installing firefox into /opt, so if 
I were you, I'd double-check that legacyfox is installed in the correct 
location. ;-)

**Comment by girst** [comment]
i'll close this, since i haven't heard back from you. feel free to open it back up when you have the time to work on it.

**Comment by ZWindL** [comment]
That's the installation logs with new profile.
![Screenshot_20220608_225504](https://user-images.githubusercontent.com/5116996/172649334-c58d3184-ee9b-4000-8578-40e3b239d8da.png)

the line of these are installation from a downloaded vimfx.xpi
```
Structured Ingestion ping failure with error: error 8 PingCentre.jsm:140
    sendStructuredIngestionPing resource:///modules/PingCentre.jsm:140
debuggee 'resource://devtools/shared/loader/base-loader.js:291' would run 4 builtin-modules.js:209:11
Uncaught (in promise) TypeError: (new TypeError("can't access property \"name\", this.addon._repositoryAddon is undefined", "resource://gre/modules/addons/XPIInstall.jsm", 1680)) is not iterable
    init resource://gre/modules/addons/XPIInstall.jsm:2139
2 XPIInstall.jsm:2139:32
```

the others are logs of installing from github release page directly.

@girst Thanks again for the great project, I can't live without vimfx now!  :P

**Comment by girst** [comment]
hmmm, i'm really at a loss why this happens. did you do the 
AddonManagerPrivate console stuff before you tried to install vimfx?

On Wed, Jun 08, 2022 at 08:02:54AM -0700, zwindl wrote:
>That's the installation logs with new profile.
>![Screenshot_20220608_225504](https://user-images.githubusercontent.com/5116996/172649334-c58d3184-ee9b-4000-8578-40e3b239d8da.png)
>
>the line of these are installation from a downloaded vimfx.xpi
>```
>Structured Ingestion ping failure with error: error 8 PingCentre.jsm:140
>    sendStructuredIngestionPing resource:///modules/PingCentre.jsm:140
>debuggee 'resource://devtools/shared/loader/base-loader.js:291' would run 4 builtin-modules.js:209:11
>Uncaught (in promise) TypeError: (new TypeError("can't access property \"name\", this.addon._repositoryAddon is undefined", "resource://gre/modules/addons/XPIInstall.jsm", 1680)) is not iterable
>    init resource://gre/modules/addons/XPIInstall.jsm:2139
>2 XPIInstall.jsm:2139:32
>```
>
>the others are logs of installing from github release page directly.
>
***@***.*** Thanks again for the great project, I can't live without vimfx now!  :P

**Comment by ZWindL** [comment]
Yep, I did all the F12, F1, mark two checkboxes, Ctrl-shift-j stuff
> hmmm, i'm really at a loss why this happens. did you do the AddonManagerPrivate console stuff before you tried to install vimfx?

And, yeah, I also tried this one, here's the result: https://github.com/akhodakivskiy/VimFx/issues/956#issuecomment-1150039424
> please also try this: 1. on https://github.com/akhodakivskiy/VimFx/releases/ right-click on vimfx.xpi and 'save as' 2. go to about:addons, click extensions in the left hand side, then the settings gear/wheel and 'install addon from file'. does this work?

(if there's any grammar issue, please feel free to correct me, I'm still improving English skills, thanks ;)  )

**Comment by ZWindL** [comment]
Seems like the piece of code below raised the errors:
``` javascript
 this.addon._repositoryAddon = repoAddon;
    this.name = this.name || this.addon._repositoryAddon.name;
    this.addon.appDisabled = !lazy.XPIDatabase.isUsableAddon(this.addon);
    return undefined;
```

error msg:
```
Uncaught (in promise) TypeError: (new TypeError("can't access property \"name\", this.addon._repositoryAddon is undefined", "resource://gre/modules/addons/XPIInstall.jsm", 1680)) is not iterable

**Comment by ZWindL** [comment]
Ah, didn't notice that, sorry. Just tried with a new profile with aur build, here's the console log before and after trying to install it from a downloaded xpi file.
![Screenshot_20220613_113659](https://user-images.githubusercontent.com/5116996/173275283-d9e1f6c2-eb73-45d7-b8d8-a08db8bcb4c2.png)
Seems not so much difference between them.
> what i meant was: did you do that BEFORE or AFTER you tried to install
the addon? sorry, i wasn't clear
