### ISSUE TITLE
Error on vim.window.gBrowser.loadURI

### ISSUE THREAD

**Issue by Ace-Who** [akhodakivskiy/VimFx#990]
Firefox Nightly 110.0a1, Windows 10 1903 build 18362.356

```js
// config.js
vimfx.addCommand({
  name: 'goto_about',
  description: 'Go to about:about',
}, ({vim}) => {
  vim.window.gBrowser.loadURI('about:about')
})
```

I set a shortcut `gaa` for this command. When I input `gaa`, the Browser Console reports

```
Error: Must load with a triggering Principal browser.js:1515:11
    _loadURI chrome://browser/content/browser.js:1515
    _loadURI self-hosted:1544
    loadURI chrome://browser/content/tabbrowser.js:526
    <anonymous> file:///C:/Users/AceQ/vimfx/config.js:11
    onInput chrome://vimfx/content/lib/modes.js:78
    _call chrome://vimfx/content/lib/vim.js:199
    _onInput chrome://vimfx/content/lib/vim.js:165
    consumeKeyEvent chrome://vimfx/content/lib/events.js:212
    addListeners chrome://vimfx/content/lib/events.js:52
```

Screenshot:

![image](https://user-images.githubusercontent.com/17397070/211100647-898ad96a-4fa3-42f8-bac4-602c7b35adba.png)

**Comment by girst** [comment]
On Fri, Jan 06, 2023 at 01:13:48PM -0800, Ace-Who wrote:
>  vim.window.gBrowser.loadURI('about:about')

>Error: Must load with a triggering Principal browser.js:1515:11

that's an internal firefox api, and since mozilla dropped legacy 
extensions they have started reworking a lot of api methods while at the 
same time removing the documentation about internals from 
https://developer.mozilla.org. there is a backup of the old docs at 
https://udn.realityripple.com, but that won't be of much help here 
either, since the api no longer works like what is described there.

the best ""documentation"" is https://searchfox.org, which lets you 
search in the firefox source code and find examples on how apis are used 
in the codebase.

https://searchfox.org/mozilla-central/search?q=gbrowser.loadURI gives a 
lot of examples for your specific case.

     getBrowserWindow().gBrowser.loadURI("about:blank", {
       triggeringPrincipal: Services.scriptSecurityManager.createNullPrincipal(
         {}
       ),
     });

this random example also explains the error message you got.

another tip: search for a method name, enable case-sensitivity and in 
the path field enter 'idl'. you very often find a short description of 
how to use a call above its declaration, like in this case:

https://searchfox.org/mozilla-central/source/docshell/base/nsIWebNavigation.idl#271

**Comment by Ace-Who** [comment]
@girst That helps, thank you!

**Comment by fl42v** [comment]
Note: looks like the null principal can't open stuff like about:downloads or about:reader. Also the url now needs to be constructed from string manually. I ended up with something like this:

```js
vimfx.addCommand({
  name: 'reader_mode',
  description: 'opens reader mode unconditionally',
}, ({vim}) => {
  let url = 'about:reader?url=' + vim.window.gBrowser.selectedBrowser.currentURI.spec
  vim.window.gBrowser.loadURI(Services.io.newURI(url), {
    triggeringPrincipal: Services.scriptSecurityManager.getSystemPrincipal(),
  });
})
```

**Comment by girst** [comment]
could you please update the snippet in the wiki? thanks!
